critical:
  - '/(\s|^)(critical|urgent)(\s|$)/i'

enhancement:
  - '/(\s|^)(feat|features|request|new|improve|create|build|enhancement)(\s|$)/i'

bug:
  - '/(\s|^)(bug|fix|issue|solve|correct|defect)(\s|$)/i'

documentation:
  - '/(\s|^)(docs|document|documentation|readme)(\s|$)/i'

help wanted:
  - '/(\s|^)(help|need)(\s|$)/i'

invalid:
  - '/(\s|^)(invalid)(\s|$)/i'

question:
  - '/(\s|^)(query|\?|question|ask)(\s|$)/i'

database:
  - '/(sql|database)/i'

Engine:
  - '/(\s|^)(core)(\s|$)/i'

TV:
  - '/(\s|^)(TV|TVE|radio|EPG)(\s|$)/i'

Tuning:
  - '/(\s|^)(tuning)(\s|$)/i'

MPE:
  - '/(\s|^)(MPE)(\s|$)/i'

Skin:
  - '/(\s|^)(Titan|DWHD|skins?)(\s|$)/i'
