critical:
  - '/(critical|urgent)/i'

enhancement:
  - '/(feat|features|request|new|improve|create|build|enhancement)/i'

bug:
  - '/(bug|fix|issue|solve|correct|defect)/i'

documentation:
  - '/(docs|document|documentation|readme)/i'

help wanted:
  - '/(help|need|info)/i'

invalid:
  - '/(invalid)/i'

question:
  - '/(query|\?|question|ask)/i'

database:
  - '/(sql|database)/i'

Engine:
  - '/(core)/i'

TV:
  - '/(TV|TVE|radio|EPG)/i'

Tuning:
  - '/(tuning)/i'

MPE:
  - '/(MPE)/i'

Skin:
  - '/(Titan|DWHD|skin)/i'
