#region Copyright (C) 2005-2011 Team MediaPortal

// Copyright (C) 2005-2011 Team MediaPortal
// http://www.team-mediaportal.com
// 
// MediaPortal is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 2 of the License, or
// (at your option) any later version.
// 
// MediaPortal is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with MediaPortal. If not, see <http://www.gnu.org/licenses/>.

#endregion

using System.Collections.ObjectModel;
using System.Collections.Generic;

namespace MediaPortal.Common.Utils.Localisation
{
  /// <summary>
  /// A class to hold the full collection of ISO 639 languages.
  /// </summary>
  public class Iso639LanguageCollection
  {
    private static Iso639LanguageCollection _instance = new Iso639LanguageCollection();

    #region languages

    /*
     * Does not include the following:
     * qaa = Original Audio [EN 300 468 annex F]
     * qad = Audio Description [EN 300 468 annex J3.2]
     * NAR = Audio Description [EN 300 468 annex J3.2]
     * 
     * Includes the following (which might not be desirable???):
     * mis = uncoded languages
     * mul = multiple languages
     * und = undetermined
     * zxx = no linguistic content, not applicable
     * 
     * Includes the following deprecated codes for backwards compatibility:
     * mol = Moldavian; Moldovan
     * scc = Serbian [Bibliographic]
     * scr = Croatian [Bibliographic]
     * jaw = Javanese
     * 
     */

    private List<Iso639Language> _languages = new List<Iso639Language>
    {
      new Iso639Language("Afar", "aa", "aar", "aar", false),
      new Iso639Language("Abkhazian", "ab", "abk", "abk", false),
      new Iso639Language("Achinese", null, "ace", "ace", false),
      new Iso639Language("Acoli", null, "ach", "ach", false),
      new Iso639Language("Adangme", null, "ada", "ada", false),
      new Iso639Language("Adyghe; Adygei", null, "ady", "ady", false),
      new Iso639Language("Afro-Asiatic languages", null, "afa", "afa", false),
      new Iso639Language("Afrihili", null, "afh", "afh", false),
      new Iso639Language("Afrikaans", "af", "afr", "afr", false),
      new Iso639Language("Ainu", null, "ain", "ain", false),
      new Iso639Language("Akan", "ak", "aka", "aka", false),
      new Iso639Language("Akkadian", null, "akk", "akk", false),
      new Iso639Language("Albanian", "sq", "alb", "sqi", false),
      new Iso639Language("Aleut", null, "ale", "ale", false),
      new Iso639Language("Algonquian languages", null, "alg", "alg", false),
      new Iso639Language("Southern Altai", null, "alt", "alt", false),
      new Iso639Language("Amharic", "am", "amh", "amh", false),
      new Iso639Language("English, Old (ca.450-1100)", null, "ang", "ang", false),
      new Iso639Language("Angika", null, "anp", "anp", false),
      new Iso639Language("Apache languages", null, "apa", "apa", false),
      new Iso639Language("Arabic", "ar", "ara", "ara", false),
      new Iso639Language("Official Aramaic (700-300 BCE); Imperial Aramaic (700-300 BCE)", null, "arc", "arc", false),
      new Iso639Language("Aragonese", "an", "arg", "arg", false),
      new Iso639Language("Armenian", "hy", "arm", "hye", false),
      new Iso639Language("Mapudungun; Mapuche", null, "arn", "arn", false),
      new Iso639Language("Arapaho", null, "arp", "arp", false),
      new Iso639Language("Artificial languages", null, "art", "art", false),
      new Iso639Language("Arawak", null, "arw", "arw", false),
      new Iso639Language("Assamese", "as", "asm", "asm", false),
      new Iso639Language("Asturian; Bable; Leonese; Asturleonese", null, "ast", "ast", false),
      new Iso639Language("Athapascan languages", null, "ath", "ath", false),
      new Iso639Language("Australian languages", null, "aus", "aus", false),
      new Iso639Language("Avaric", "av", "ava", "ava", false),
      new Iso639Language("Avestan", "ae", "ave", "ave", false),
      new Iso639Language("Awadhi", null, "awa", "awa", false),
      new Iso639Language("Aymara", "ay", "aym", "aym", false),
      new Iso639Language("Azerbaijani", "az", "aze", "aze", false),
      new Iso639Language("Banda languages", null, "bad", "bad", false),
      new Iso639Language("Bamileke languages", null, "bai", "bai", false),
      new Iso639Language("Bashkir", "ba", "bak", "bak", false),
      new Iso639Language("Baluchi", null, "bal", "bal", false),
      new Iso639Language("Bambara", "bm", "bam", "bam", false),
      new Iso639Language("Balinese", null, "ban", "ban", false),
      new Iso639Language("Basque", "eu", "baq", "eus", false),
      new Iso639Language("Basa", null, "bas", "bas", false),
      new Iso639Language("Baltic languages", null, "bat", "bat", false),
      new Iso639Language("Beja; Bedawiyet", null, "bej", "bej", false),
      new Iso639Language("Belarusian", "be", "bel", "bel", false),
      new Iso639Language("Bemba", null, "bem", "bem", false),
      new Iso639Language("Bengali", "bn", "ben", "ben", false),
      new Iso639Language("Berber languages", null, "ber", "ber", false),
      new Iso639Language("Bhojpuri", null, "bho", "bho", false),
      new Iso639Language("Bihari languages", "bh", "bih", "bih", false),
      new Iso639Language("Bikol", null, "bik", "bik", false),
      new Iso639Language("Bini; Edo", null, "bin", "bin", false),
      new Iso639Language("Bislama", "bi", "bis", "bis", false),
      new Iso639Language("Siksika", null, "bla", "bla", false),
      new Iso639Language("Bantu languages", null, "bnt", "bnt", false),
      new Iso639Language("Bosnian", "bs", "bos", "bos", false),
      new Iso639Language("Braj", null, "bra", "bra", false),
      new Iso639Language("Breton", "br", "bre", "bre", false),
      new Iso639Language("Batak languages", null, "btk", "btk", false),
      new Iso639Language("Buriat", null, "bua", "bua", false),
      new Iso639Language("Buginese", null, "bug", "bug", false),
      new Iso639Language("Bulgarian", "bg", "bul", "bul", false),
      new Iso639Language("Burmese", "my", "bur", "mya", false),
      new Iso639Language("Blin; Bilin", null, "byn", "byn", false),
      new Iso639Language("Caddo", null, "cad", "cad", false),
      new Iso639Language("Central American Indian languages", null, "cai", "cai", false),
      new Iso639Language("Galibi Carib", null, "car", "car", false),
      new Iso639Language("Catalan; Valencian", "ca", "cat", "cat", false),
      new Iso639Language("Caucasian languages", null, "cau", "cau", false),
      new Iso639Language("Cebuano", null, "ceb", "ceb", false),
      new Iso639Language("Celtic languages", null, "cel", "cel", false),
      new Iso639Language("Chamorro", "ch", "cha", "cha", false),
      new Iso639Language("Chibcha", null, "chb", "chb", false),
      new Iso639Language("Chechen", "ce", "che", "che", false),
      new Iso639Language("Chagatai", null, "chg", "chg", false),
      new Iso639Language("Chinese", "zh", "chi", "zho", false),
      new Iso639Language("Chuukese", null, "chk", "chk", false),
      new Iso639Language("Mari", null, "chm", "chm", false),
      new Iso639Language("Chinook jargon", null, "chn", "chn", false),
      new Iso639Language("Choctaw", null, "cho", "cho", false),
      new Iso639Language("Chipewyan; Dene Suline", null, "chp", "chp", false),
      new Iso639Language("Cherokee", null, "chr", "chr", false),
      new Iso639Language("Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic", "cu", "chu", "chu", false),
      new Iso639Language("Chuvash", "cv", "chv", "chv", false),
      new Iso639Language("Cheyenne", null, "chy", "chy", false),
      new Iso639Language("Chamic languages", null, "cmc", "cmc", false),
      new Iso639Language("Coptic", null, "cop", "cop", false),
      new Iso639Language("Cornish", "kw", "cor", "cor", false),
      new Iso639Language("Corsican", "co", "cos", "cos", false),
      new Iso639Language("Creoles and pidgins, English based", null, "cpe", "cpe", false),
      new Iso639Language("Creoles and pidgins, French-based", null, "cpf", "cpf", false),
      new Iso639Language("Creoles and pidgins, Portuguese-based", null, "cpp", "cpp", false),
      new Iso639Language("Cree", "cr", "cre", "cre", false),
      new Iso639Language("Crimean Tatar; Crimean Turkish", null, "crh", "crh", false),
      new Iso639Language("Creoles and pidgins", null, "crp", "crp", false),
      new Iso639Language("Kashubian", null, "csb", "csb", false),
      new Iso639Language("Cushitic languages", null, "cus", "cus", false),
      new Iso639Language("Czech", "cs", "cze", "ces", false),
      new Iso639Language("Dakota", null, "dak", "dak", false),
      new Iso639Language("Danish", "da", "dan", "dan", false),
      new Iso639Language("Dargwa", null, "dar", "dar", false),
      new Iso639Language("Land Dayak languages", null, "day", "day", false),
      new Iso639Language("Delaware", null, "del", "del", false),
      new Iso639Language("Slave (Athapascan)", null, "den", "den", false),
      new Iso639Language("Dogrib", null, "dgr", "dgr", false),
      new Iso639Language("Dinka", null, "din", "din", false),
      new Iso639Language("Divehi; Dhivehi; Maldivian", "dv", "div", "div", false),
      new Iso639Language("Dogri", null, "doi", "doi", false),
      new Iso639Language("Dravidian languages", null, "dra", "dra", false),
      new Iso639Language("Lower Sorbian", null, "dsb", "dsb", false),
      new Iso639Language("Duala", null, "dua", "dua", false),
      new Iso639Language("Dutch, Middle (ca.1050-1350)", null, "dum", "dum", false),
      new Iso639Language("Dutch; Flemish", "nl", "dut", "nld", false),
      new Iso639Language("Dyula", null, "dyu", "dyu", false),
      new Iso639Language("Dzongkha", "dz", "dzo", "dzo", false),
      new Iso639Language("Efik", null, "efi", "efi", false),
      new Iso639Language("Egyptian (Ancient)", null, "egy", "egy", false),
      new Iso639Language("Ekajuk", null, "eka", "eka", false),
      new Iso639Language("Elamite", null, "elx", "elx", false),
      new Iso639Language("English", "en", "eng", "eng", false),
      new Iso639Language("English, Middle (1100-1500)", null, "enm", "enm", false),
      new Iso639Language("Esperanto", "eo", "epo", "epo", false),
      new Iso639Language("Estonian", "et", "est", "est", false),
      new Iso639Language("Ewe", "ee", "ewe", "ewe", false),
      new Iso639Language("Ewondo", null, "ewo", "ewo", false),
      new Iso639Language("Fang", null, "fan", "fan", false),
      new Iso639Language("Faroese", "fo", "fao", "fao", false),
      new Iso639Language("Fanti", null, "fat", "fat", false),
      new Iso639Language("Fijian", "fj", "fij", "fij", false),
      new Iso639Language("Filipino; Pilipino", null, "fil", "fil", false),
      new Iso639Language("Finnish", "fi", "fin", "fin", false),
      new Iso639Language("Finno-Ugrian languages", null, "fiu", "fiu", false),
      new Iso639Language("Fon", null, "fon", "fon", false),
      new Iso639Language("French", "fr", "fre", "fra", false),
      new Iso639Language("French, Middle (ca.1400-1600)", null, "frm", "frm", false),
      new Iso639Language("French, Old (842-ca.1400)", null, "fro", "fro", false),
      new Iso639Language("Northern Frisian", null, "frr", "frr", false),
      new Iso639Language("Eastern Frisian", null, "frs", "frs", false),
      new Iso639Language("Western Frisian", "fy", "fry", "fry", false),
      new Iso639Language("Fulah", "ff", "ful", "ful", false),
      new Iso639Language("Friulian", null, "fur", "fur", false),
      new Iso639Language("Ga", null, "gaa", "gaa", false),
      new Iso639Language("Gayo", null, "gay", "gay", false),
      new Iso639Language("Gbaya", null, "gba", "gba", false),
      new Iso639Language("Germanic languages", null, "gem", "gem", false),
      new Iso639Language("Georgian", "ka", "geo", "kat", false),
      new Iso639Language("German", "de", "ger", "deu", false),
      new Iso639Language("Geez", null, "gez", "gez", false),
      new Iso639Language("Gilbertese", null, "gil", "gil", false),
      new Iso639Language("Gaelic; Scottish Gaelic", "gd", "gla", "gla", false),
      new Iso639Language("Irish", "ga", "gle", "gle", false),
      new Iso639Language("Galician", "gl", "glg", "glg", false),
      new Iso639Language("Manx", "gv", "glv", "glv", false),
      new Iso639Language("German, Middle High (ca.1050-1500)", null, "gmh", "gmh", false),
      new Iso639Language("German, Old High (ca.750-1050)", null, "goh", "goh", false),
      new Iso639Language("Gondi", null, "gon", "gon", false),
      new Iso639Language("Gorontalo", null, "gor", "gor", false),
      new Iso639Language("Gothic", null, "got", "got", false),
      new Iso639Language("Grebo", null, "grb", "grb", false),
      new Iso639Language("Greek, Ancient (to 1453)", null, "grc", "grc", false),
      new Iso639Language("Greek, Modern (1453-)", "el", "gre", "ell", false),
      new Iso639Language("Guarani", "gn", "grn", "grn", false),
      new Iso639Language("Swiss German; Alemannic; Alsatian", null, "gsw", "gsw", false),
      new Iso639Language("Gujarati", "gu", "guj", "guj", false),
      new Iso639Language("Gwich'in", null, "gwi", "gwi", false),
      new Iso639Language("Haida", null, "hai", "hai", false),
      new Iso639Language("Haitian; Haitian Creole", "ht", "hat", "hat", false),
      new Iso639Language("Hausa", "ha", "hau", "hau", false),
      new Iso639Language("Hawaiian", null, "haw", "haw", false),
      new Iso639Language("Hebrew", "he", "heb", "heb", false),
      new Iso639Language("Herero", "hz", "her", "her", false),
      new Iso639Language("Hiligaynon", null, "hil", "hil", false),
      new Iso639Language("Himachali languages; Western Pahari languages", null, "him", "him", false),
      new Iso639Language("Hindi", "hi", "hin", "hin", false),
      new Iso639Language("Hittite", null, "hit", "hit", false),
      new Iso639Language("Hmong; Mong", null, "hmn", "hmn", false),
      new Iso639Language("Hiri Motu", "ho", "hmo", "hmo", false),
      new Iso639Language("Croatian", "hr", "scr", "hrv", true),
      new Iso639Language("Upper Sorbian", null, "hsb", "hsb", false),
      new Iso639Language("Hungarian", "hu", "hun", "hun", false),
      new Iso639Language("Hupa", null, "hup", "hup", false),
      new Iso639Language("Iban", null, "iba", "iba", false),
      new Iso639Language("Igbo", "ig", "ibo", "ibo", false),
      new Iso639Language("Icelandic", "is", "ice", "isl", false),
      new Iso639Language("Ido", "io", "ido", "ido", false),
      new Iso639Language("Sichuan Yi; Nuosu", "ii", "iii", "iii", false),
      new Iso639Language("Ijo languages", null, "ijo", "ijo", false),
      new Iso639Language("Inuktitut", "iu", "iku", "iku", false),
      new Iso639Language("Interlingue; Occidental", "ie", "ile", "ile", false),
      new Iso639Language("Iloko", null, "ilo", "ilo", false),
      new Iso639Language("Interlingua (International Auxiliary Language Association)", "ia", "ina", "ina", false),
      new Iso639Language("Indic languages", null, "inc", "inc", false),
      new Iso639Language("Indonesian", "id", "ind", "ind", false),
      new Iso639Language("Indo-European languages", null, "ine", "ine", false),
      new Iso639Language("Ingush", null, "inh", "inh", false),
      new Iso639Language("Inupiaq", "ik", "ipk", "ipk", false),
      new Iso639Language("Iranian languages", null, "ira", "ira", false),
      new Iso639Language("Iroquoian languages", null, "iro", "iro", false),
      new Iso639Language("Italian", "it", "ita", "ita", false),
      new Iso639Language("Javanese", "jv", "jav", "jav", false),
      new Iso639Language("Lojban", null, "jbo", "jbo", false),
      new Iso639Language("Japanese", "ja", "jpn", "jpn", false),
      new Iso639Language("Judeo-Persian", null, "jpr", "jpr", false),
      new Iso639Language("Judeo-Arabic", null, "jrb", "jrb", false),
      new Iso639Language("Kara-Kalpak", null, "kaa", "kaa", false),
      new Iso639Language("Kabyle", null, "kab", "kab", false),
      new Iso639Language("Kachin; Jingpho", null, "kac", "kac", false),
      new Iso639Language("Kalaallisut; Greenlandic", "kl", "kal", "kal", false),
      new Iso639Language("Kamba", null, "kam", "kam", false),
      new Iso639Language("Kannada", "kn", "kan", "kan", false),
      new Iso639Language("Karen languages", null, "kar", "kar", false),
      new Iso639Language("Kashmiri", "ks", "kas", "kas", false),
      new Iso639Language("Kanuri", "kr", "kau", "kau", false),
      new Iso639Language("Kawi", null, "kaw", "kaw", false),
      new Iso639Language("Kazakh", "kk", "kaz", "kaz", false),
      new Iso639Language("Kabardian", null, "kbd", "kbd", false),
      new Iso639Language("Khasi", null, "kha", "kha", false),
      new Iso639Language("Khoisan languages", null, "khi", "khi", false),
      new Iso639Language("Central Khmer", "km", "khm", "khm", false),
      new Iso639Language("Khotanese; Sakan", null, "kho", "kho", false),
      new Iso639Language("Kikuyu; Gikuyu", "ki", "kik", "kik", false),
      new Iso639Language("Kinyarwanda", "rw", "kin", "kin", false),
      new Iso639Language("Kirghiz; Kyrgyz", "ky", "kir", "kir", false),
      new Iso639Language("Kimbundu", null, "kmb", "kmb", false),
      new Iso639Language("Konkani", null, "kok", "kok", false),
      new Iso639Language("Komi", "kv", "kom", "kom", false),
      new Iso639Language("Kongo", "kg", "kon", "kon", false),
      new Iso639Language("Korean", "ko", "kor", "kor", false),
      new Iso639Language("Kosraean", null, "kos", "kos", false),
      new Iso639Language("Kpelle", null, "kpe", "kpe", false),
      new Iso639Language("Karachay-Balkar", null, "krc", "krc", false),
      new Iso639Language("Karelian", null, "krl", "krl", false),
      new Iso639Language("Kru languages", null, "kro", "kro", false),
      new Iso639Language("Kurukh", null, "kru", "kru", false),
      new Iso639Language("Kuanyama; Kwanyama", "kj", "kua", "kua", false),
      new Iso639Language("Kumyk", null, "kum", "kum", false),
      new Iso639Language("Kurdish", "ku", "kur", "kur", false),
      new Iso639Language("Kutenai", null, "kut", "kut", false),
      new Iso639Language("Ladino", null, "lad", "lad", false),
      new Iso639Language("Lahnda", null, "lah", "lah", false),
      new Iso639Language("Lamba", null, "lam", "lam", false),
      new Iso639Language("Lao", "lo", "lao", "lao", false),
      new Iso639Language("Latin", "la", "lat", "lat", false),
      new Iso639Language("Latvian", "lv", "lav", "lav", false),
      new Iso639Language("Lezghian", null, "lez", "lez", false),
      new Iso639Language("Limburgan; Limburger; Limburgish", "li", "lim", "lim", false),
      new Iso639Language("Lingala", "ln", "lin", "lin", false),
      new Iso639Language("Lithuanian", "lt", "lit", "lit", false),
      new Iso639Language("Mongo", null, "lol", "lol", false),
      new Iso639Language("Lozi", null, "loz", "loz", false),
      new Iso639Language("Luxembourgish; Letzeburgesch", "lb", "ltz", "ltz", false),
      new Iso639Language("Luba-Lulua", null, "lua", "lua", false),
      new Iso639Language("Luba-Katanga", "lu", "lub", "lub", false),
      new Iso639Language("Ganda", "lg", "lug", "lug", false),
      new Iso639Language("Luiseno", null, "lui", "lui", false),
      new Iso639Language("Lunda", null, "lun", "lun", false),
      new Iso639Language("Luo (Kenya and Tanzania)", null, "luo", "luo", false),
      new Iso639Language("Lushai", null, "lus", "lus", false),
      new Iso639Language("Macedonian", "mk", "mac", "mkd", false),
      new Iso639Language("Madurese", null, "mad", "mad", false),
      new Iso639Language("Magahi", null, "mag", "mag", false),
      new Iso639Language("Marshallese", "mh", "mah", "mah", false),
      new Iso639Language("Maithili", null, "mai", "mai", false),
      new Iso639Language("Makasar", null, "mak", "mak", false),
      new Iso639Language("Malayalam", "ml", "mal", "mal", false),
      new Iso639Language("Mandingo", null, "man", "man", false),
      new Iso639Language("Maori", "mi", "mao", "mri", false),
      new Iso639Language("Austronesian languages", null, "map", "map", false),
      new Iso639Language("Marathi", "mr", "mar", "mar", false),
      new Iso639Language("Masai", null, "mas", "mas", false),
      new Iso639Language("Malay", "ms", "may", "msa", false),
      new Iso639Language("Moksha", null, "mdf", "mdf", false),
      new Iso639Language("Mandar", null, "mdr", "mdr", false),
      new Iso639Language("Mende", null, "men", "men", false),
      new Iso639Language("Irish, Middle (900-1200)", null, "mga", "mga", false),
      new Iso639Language("Mi'kmaq; Micmac", null, "mic", "mic", false),
      new Iso639Language("Minangkabau", null, "min", "min", false),
      new Iso639Language("Uncoded languages", null, "mis", "mis", false),
      new Iso639Language("Mon-Khmer languages", null, "mkh", "mkh", false),
      new Iso639Language("Malagasy", "mg", "mlg", "mlg", false),
      new Iso639Language("Maltese", "mt", "mlt", "mlt", false),
      new Iso639Language("Manchu", null, "mnc", "mnc", false),
      new Iso639Language("Manipuri", null, "mni", "mni", false),
      new Iso639Language("Manobo languages", null, "mno", "mno", false),
      new Iso639Language("Mohawk", null, "moh", "moh", false),
      new Iso639Language("Mongolian", "mn", "mon", "mon", false),
      new Iso639Language("Mossi", null, "mos", "mos", false),
      new Iso639Language("Multiple languages", null, "mul", "mul", false),
      new Iso639Language("Munda languages", null, "mun", "mun", false),
      new Iso639Language("Creek", null, "mus", "mus", false),
      new Iso639Language("Mirandese", null, "mwl", "mwl", false),
      new Iso639Language("Marwari", null, "mwr", "mwr", false),
      new Iso639Language("Mayan languages", null, "myn", "myn", false),
      new Iso639Language("Erzya", null, "myv", "myv", false),
      new Iso639Language("Nahuatl languages", null, "nah", "nah", false),
      new Iso639Language("North American Indian languages", null, "nai", "nai", false),
      new Iso639Language("Neapolitan", null, "nap", "nap", false),
      new Iso639Language("Nauru", "na", "nau", "nau", false),
      new Iso639Language("Navajo; Navaho", "nv", "nav", "nav", false),
      new Iso639Language("Ndebele, South; South Ndebele", "nr", "nbl", "nbl", false),
      new Iso639Language("Ndebele, North; North Ndebele", "nd", "nde", "nde", false),
      new Iso639Language("Ndonga", "ng", "ndo", "ndo", false),
      new Iso639Language("Low German; Low Saxon; German, Low; Saxon, Low", null, "nds", "nds", false),
      new Iso639Language("Nepali", "ne", "nep", "nep", false),
      new Iso639Language("Nepal Bhasa; Newari", null, "new", "new", false),
      new Iso639Language("Nias", null, "nia", "nia", false),
      new Iso639Language("Niger-Kordofanian languages", null, "nic", "nic", false),
      new Iso639Language("Niuean", null, "niu", "niu", false),
      new Iso639Language("Norwegian Nynorsk; Nynorsk, Norwegian", "nn", "nno", "nno", false),
      new Iso639Language("Bokmål, Norwegian; Norwegian Bokmål", "nb", "nob", "nob", false),
      new Iso639Language("Nogai", null, "nog", "nog", false),
      new Iso639Language("Norse, Old", null, "non", "non", false),
      new Iso639Language("Norwegian", "no", "nor", "nor", false),
      new Iso639Language("N'Ko", null, "nqo", "nqo", false),
      new Iso639Language("Pedi; Sepedi; Northern Sotho", null, "nso", "nso", false),
      new Iso639Language("Nubian languages", null, "nub", "nub", false),
      new Iso639Language("Classical Newari; Old Newari; Classical Nepal Bhasa", null, "nwc", "nwc", false),
      new Iso639Language("Chichewa; Chewa; Nyanja", "ny", "nya", "nya", false),
      new Iso639Language("Nyamwezi", null, "nym", "nym", false),
      new Iso639Language("Nyankole", null, "nyn", "nyn", false),
      new Iso639Language("Nyoro", null, "nyo", "nyo", false),
      new Iso639Language("Nzima", null, "nzi", "nzi", false),
      new Iso639Language("Occitan (post 1500)", "oc", "oci", "oci", false),
      new Iso639Language("Ojibwa", "oj", "oji", "oji", false),
      new Iso639Language("Oriya", "or", "ori", "ori", false),
      new Iso639Language("Oromo", "om", "orm", "orm", false),
      new Iso639Language("Osage", null, "osa", "osa", false),
      new Iso639Language("Ossetian; Ossetic", "os", "oss", "oss", false),
      new Iso639Language("Turkish, Ottoman (1500-1928)", null, "ota", "ota", false),
      new Iso639Language("Otomian languages", null, "oto", "oto", false),
      new Iso639Language("Papuan languages", null, "paa", "paa", false),
      new Iso639Language("Pangasinan", null, "pag", "pag", false),
      new Iso639Language("Pahlavi", null, "pal", "pal", false),
      new Iso639Language("Pampanga; Kapampangan", null, "pam", "pam", false),
      new Iso639Language("Panjabi; Punjabi", "pa", "pan", "pan", false),
      new Iso639Language("Papiamento", null, "pap", "pap", false),
      new Iso639Language("Palauan", null, "pau", "pau", false),
      new Iso639Language("Persian, Old (ca.600-400 B.C.)", null, "peo", "peo", false),
      new Iso639Language("Persian", "fa", "per", "fas", false),
      new Iso639Language("Philippine languages", null, "phi", "phi", false),
      new Iso639Language("Phoenician", null, "phn", "phn", false),
      new Iso639Language("Pali", "pi", "pli", "pli", false),
      new Iso639Language("Polish", "pl", "pol", "pol", false),
      new Iso639Language("Pohnpeian", null, "pon", "pon", false),
      new Iso639Language("Portuguese", "pt", "por", "por", false),
      new Iso639Language("Prakrit languages", null, "pra", "pra", false),
      new Iso639Language("Provençal, Old (to 1500); Occitan, Old (to 1500)", null, "pro", "pro", false),
      new Iso639Language("Pushto; Pashto", "ps", "pus", "pus", false),
      new Iso639Language("Quechua", "qu", "que", "que", false),
      new Iso639Language("Rajasthani", null, "raj", "raj", false),
      new Iso639Language("Rapanui", null, "rap", "rap", false),
      new Iso639Language("Rarotongan; Cook Islands Maori", null, "rar", "rar", false),
      new Iso639Language("Romance languages", null, "roa", "roa", false),
      new Iso639Language("Romansh", "rm", "roh", "roh", false),
      new Iso639Language("Romany", null, "rom", "rom", false),
      new Iso639Language("Romanian", "ro", "rum", "ron", false),
      new Iso639Language("Rundi", "rn", "run", "run", false),
      new Iso639Language("Aromanian; Arumanian; Macedo-Romanian", null, "rup", "rup", false),
      new Iso639Language("Russian", "ru", "rus", "rus", false),
      new Iso639Language("Sandawe", null, "sad", "sad", false),
      new Iso639Language("Sango", "sg", "sag", "sag", false),
      new Iso639Language("Yakut", null, "sah", "sah", false),
      new Iso639Language("South American Indian languages", null, "sai", "sai", false),
      new Iso639Language("Salishan languages", null, "sal", "sal", false),
      new Iso639Language("Samaritan Aramaic", null, "sam", "sam", false),
      new Iso639Language("Sanskrit", "sa", "san", "san", false),
      new Iso639Language("Sasak", null, "sas", "sas", false),
      new Iso639Language("Santali", null, "sat", "sat", false),
      new Iso639Language("Sicilian", null, "scn", "scn", false),
      new Iso639Language("Scots", null, "sco", "sco", false),
      new Iso639Language("Selkup", null, "sel", "sel", false),
      new Iso639Language("Semitic languages", null, "sem", "sem", false),
      new Iso639Language("Irish, Old (to 900)", null, "sga", "sga", false),
      new Iso639Language("Sign Languages", null, "sgn", "sgn", false),
      new Iso639Language("Shan", null, "shn", "shn", false),
      new Iso639Language("Sidamo", null, "sid", "sid", false),
      new Iso639Language("Sinhala; Sinhalese", "si", "sin", "sin", false),
      new Iso639Language("Siouan languages", null, "sio", "sio", false),
      new Iso639Language("Sino-Tibetan languages", null, "sit", "sit", false),
      new Iso639Language("Slavic languages", null, "sla", "sla", false),
      new Iso639Language("Slovak", "sk", "slo", "slk", false),
      new Iso639Language("Slovenian", "sl", "slv", "slv", false),
      new Iso639Language("Southern Sami", null, "sma", "sma", false),
      new Iso639Language("Northern Sami", "se", "sme", "sme", false),
      new Iso639Language("Sami languages", null, "smi", "smi", false),
      new Iso639Language("Lule Sami", null, "smj", "smj", false),
      new Iso639Language("Inari Sami", null, "smn", "smn", false),
      new Iso639Language("Samoan", "sm", "smo", "smo", false),
      new Iso639Language("Skolt Sami", null, "sms", "sms", false),
      new Iso639Language("Shona", "sn", "sna", "sna", false),
      new Iso639Language("Sindhi", "sd", "snd", "snd", false),
      new Iso639Language("Soninke", null, "snk", "snk", false),
      new Iso639Language("Sogdian", null, "sog", "sog", false),
      new Iso639Language("Somali", "so", "som", "som", false),
      new Iso639Language("Songhai languages", null, "son", "son", false),
      new Iso639Language("Sotho, Southern", "st", "sot", "sot", false),
      new Iso639Language("Spanish; Castilian", "es", "spa", "spa", false),
      new Iso639Language("Sardinian", "sc", "srd", "srd", false),
      new Iso639Language("Sranan Tongo", null, "srn", "srn", false),
      new Iso639Language("Serbian", "sr", "scc", "srp", true),
      new Iso639Language("Serer", null, "srr", "srr", false),
      new Iso639Language("Nilo-Saharan languages", null, "ssa", "ssa", false),
      new Iso639Language("Swati", "ss", "ssw", "ssw", false),
      new Iso639Language("Sukuma", null, "suk", "suk", false),
      new Iso639Language("Sundanese", "su", "sun", "sun", false),
      new Iso639Language("Susu", null, "sus", "sus", false),
      new Iso639Language("Sumerian", null, "sux", "sux", false),
      new Iso639Language("Swahili", "sw", "swa", "swa", false),
      new Iso639Language("Swedish", "sv", "swe", "swe", false),
      new Iso639Language("Classical Syriac", null, "syc", "syc", false),
      new Iso639Language("Syriac", null, "syr", "syr", false),
      new Iso639Language("Tahitian", "ty", "tah", "tah", false),
      new Iso639Language("Tai languages", null, "tai", "tai", false),
      new Iso639Language("Tamil", "ta", "tam", "tam", false),
      new Iso639Language("Tatar", "tt", "tat", "tat", false),
      new Iso639Language("Telugu", "te", "tel", "tel", false),
      new Iso639Language("Timne", null, "tem", "tem", false),
      new Iso639Language("Tereno", null, "ter", "ter", false),
      new Iso639Language("Tetum", null, "tet", "tet", false),
      new Iso639Language("Tajik", "tg", "tgk", "tgk", false),
      new Iso639Language("Tagalog", "tl", "tgl", "tgl", false),
      new Iso639Language("Thai", "th", "tha", "tha", false),
      new Iso639Language("Tibetan", "bo", "tib", "bod", false),
      new Iso639Language("Tigre", null, "tig", "tig", false),
      new Iso639Language("Tigrinya", "ti", "tir", "tir", false),
      new Iso639Language("Tiv", null, "tiv", "tiv", false),
      new Iso639Language("Tokelau", null, "tkl", "tkl", false),
      new Iso639Language("Klingon; tlhIngan-Hol", null, "tlh", "tlh", false),
      new Iso639Language("Tlingit", null, "tli", "tli", false),
      new Iso639Language("Tamashek", null, "tmh", "tmh", false),
      new Iso639Language("Tonga (Nyasa)", null, "tog", "tog", false),
      new Iso639Language("Tonga (Tonga Islands)", "to", "ton", "ton", false),
      new Iso639Language("Tok Pisin", null, "tpi", "tpi", false),
      new Iso639Language("Tsimshian", null, "tsi", "tsi", false),
      new Iso639Language("Tswana", "tn", "tsn", "tsn", false),
      new Iso639Language("Tsonga", "ts", "tso", "tso", false),
      new Iso639Language("Turkmen", "tk", "tuk", "tuk", false),
      new Iso639Language("Tumbuka", null, "tum", "tum", false),
      new Iso639Language("Tupi languages", null, "tup", "tup", false),
      new Iso639Language("Turkish", "tr", "tur", "tur", false),
      new Iso639Language("Altaic languages", null, "tut", "tut", false),
      new Iso639Language("Tuvalu", null, "tvl", "tvl", false),
      new Iso639Language("Twi", "tw", "twi", "twi", false),
      new Iso639Language("Tuvinian", null, "tyv", "tyv", false),
      new Iso639Language("Udmurt", null, "udm", "udm", false),
      new Iso639Language("Ugaritic", null, "uga", "uga", false),
      new Iso639Language("Uighur; Uyghur", "ug", "uig", "uig", false),
      new Iso639Language("Ukrainian", "uk", "ukr", "ukr", false),
      new Iso639Language("Umbundu", null, "umb", "umb", false),
      new Iso639Language("Undetermined", null, "und", "und", false),
      new Iso639Language("Urdu", "ur", "urd", "urd", false),
      new Iso639Language("Uzbek", "uz", "uzb", "uzb", false),
      new Iso639Language("Vai", null, "vai", "vai", false),
      new Iso639Language("Venda", "ve", "ven", "ven", false),
      new Iso639Language("Vietnamese", "vi", "vie", "vie", false),
      new Iso639Language("Volapük", "vo", "vol", "vol", false),
      new Iso639Language("Votic", null, "vot", "vot", false),
      new Iso639Language("Wakashan languages", null, "wak", "wak", false),
      new Iso639Language("Wolaitta; Wolaytta", null, "wal", "wal", false),
      new Iso639Language("Waray", null, "war", "war", false),
      new Iso639Language("Washo", null, "was", "was", false),
      new Iso639Language("Welsh", "cy", "wel", "cym", false),
      new Iso639Language("Sorbian languages", null, "wen", "wen", false),
      new Iso639Language("Walloon", "wa", "wln", "wln", false),
      new Iso639Language("Wolof", "wo", "wol", "wol", false),
      new Iso639Language("Kalmyk; Oirat", null, "xal", "xal", false),
      new Iso639Language("Xhosa", "xh", "xho", "xho", false),
      new Iso639Language("Yao", null, "yao", "yao", false),
      new Iso639Language("Yapese", null, "yap", "yap", false),
      new Iso639Language("Yiddish", "yi", "yid", "yid", false),
      new Iso639Language("Yoruba", "yo", "yor", "yor", false),
      new Iso639Language("Yupik languages", null, "ypk", "ypk", false),
      new Iso639Language("Zapotec", null, "zap", "zap", false),
      new Iso639Language("Blissymbols; Blissymbolics; Bliss", null, "zbl", "zbl", false),
      new Iso639Language("Zenaga", null, "zen", "zen", false),
      new Iso639Language("Standard Moroccan Tamazight", null, "zgh", "zgh", false),
      new Iso639Language("Zhuang; Chuang", "za", "zha", "zha", false),
      new Iso639Language("Zande languages", null, "znd", "znd", false),
      new Iso639Language("Zulu", "zu", "zul", "zul", false),
      new Iso639Language("Zuni", null, "zun", "zun", false),
      new Iso639Language("No linguistic content; Not applicable", null, "zxx", "zxx", false),
      new Iso639Language("Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki", null, "zza", "zza", false),

      // Deprecated codes, included for backwards compatibility.
      new Iso639Language("Javanese [alt]", "jw", "jaw", null, true),
      new Iso639Language("Moldavian; Moldovan", "mo", "mol", null, true)
    };

    #endregion

    /// <summary>
    /// A static method to access the singleton instance of this class.
    /// </summary>
    public static Iso639LanguageCollection Instance
    {
      get
      {
        return _instance;
      }
    }

    /// <summary>
    /// Constructor, private since this is a singleton class.
    /// </summary>
    private Iso639LanguageCollection()
    {
    }

    /// <summary>
    /// Get the full ISO 639 language list.
    /// </summary>
    public ReadOnlyCollection<Iso639Language> Languages
    {
      get
      {
        return _languages.AsReadOnly();
      }
    }

    /// <summary>
    /// Find a language based on its unique ISO 639-2 code.
    /// </summary>
    /// <param name="threeLetterCode">The ISO 639-2 code.</param>
    /// <returns>a language instance if the code is found in the ISO 639 language list, otherwise <c>null</c></returns>
    public Iso639Language GetLanguageFromThreeLetterCode(string threeLetterCode)
    {
      if (string.IsNullOrEmpty(threeLetterCode))
      {
        return null;
      }
      foreach (Iso639Language l in _languages)
      {
        if (l.BibliographicCode.Equals(threeLetterCode) || l.TerminologicCode.Equals(threeLetterCode))
        {
          return l;
        }
      }
      return null;
    }
  }
}