/******************************************************************************
*
*   File:           US2CIiface.idl
*   Written by:     Smardtv
*
*   Copyright (C) 2006 Smardtv
*
*	Version 2.0
*
*******************************************************************************/

import "unknwn.idl";
import "strmif.idl";


#ifdef HAUPPAUGE_VERSION
[uuid( C29D9628-AE8B-430d-90B4-10D6EAF2F210 ),
#else
[uuid( 1FAF5E40-543D-406b-82F9-AABFAB41ECA1 ),
#endif

 version( 1.22 ),
 helpstring( "USB2CI BDA type library" ),
 control]

library USB2CIBDA
{
    [
        object,
		#ifdef HAUPPAUGE_VERSION
		uuid( DD5A9B44-348A-4607-BF72-CFD8239E4432 ),
		#else
		uuid( A934E61E-2E24-4145-B45B-3E71830048F7 ),
		#endif        
        pointer_default(unique)
    ] 

		interface IUSB2CIBDAConfig : IUnknown
    {
		HRESULT	USB2CI_Init( [in] PVOID  pCallBack);
		HRESULT	USB2CI_OpenMMI( void );
		HRESULT USB2CI_APDUToCAM( long SizeofAPDU, char* APDU);
		HRESULT	USB2CI_GuiSendPMT( [in] char* pPMT, [in] short Size);
		HRESULT USB2CI_GetVersion( [in] PVOID VersionTab);
    };


    [
		#ifdef HAUPPAUGE_VERSION
		uuid (8BF24573-E336-4986-B306-0C7EFB7E5823 ),
		#else
		uuid( 9076F340-7529-4d09-A9BB-349AE1FF96E2 ),
		#endif        
        helpstring( "USB2CIBDA Page Class" )
    ]


    coclass USB2CIBDAPage
    {
        [default] interface IPropertyPage;
    };
};
