//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TVDatabaseEntities
{
    public partial class CardGroupMap
    {
        #region Primitive Properties
    
        public virtual int idMapping
        {
            get;
            set;
        }
    
        public virtual int idCard
        {
            get { return _idCard; }
            set
            {
                if (_idCard != value)
                {
                    if (Card != null && Card.idCard != value)
                    {
                        Card = null;
                    }
                    _idCard = value;
                }
            }
        }
        private int _idCard;
    
        public virtual int idCardGroup
        {
            get { return _idCardGroup; }
            set
            {
                if (_idCardGroup != value)
                {
                    if (CardGroup != null && CardGroup.idCardGroup != value)
                    {
                        CardGroup = null;
                    }
                    _idCardGroup = value;
                }
            }
        }
        private int _idCardGroup;

        #endregion
        #region Navigation Properties
    
        public virtual Card Card
        {
            get { return _card; }
            set
            {
                if (!ReferenceEquals(_card, value))
                {
                    var previousValue = _card;
                    _card = value;
                    FixupCard(previousValue);
                }
            }
        }
        private Card _card;
    
        public virtual CardGroup CardGroup
        {
            get { return _cardGroup; }
            set
            {
                if (!ReferenceEquals(_cardGroup, value))
                {
                    var previousValue = _cardGroup;
                    _cardGroup = value;
                    FixupCardGroup(previousValue);
                }
            }
        }
        private CardGroup _cardGroup;

        #endregion
        #region Association Fixup
    
        private void FixupCard(Card previousValue)
        {
            if (previousValue != null && previousValue.CardGroupMaps.Contains(this))
            {
                previousValue.CardGroupMaps.Remove(this);
            }
    
            if (Card != null)
            {
                if (!Card.CardGroupMaps.Contains(this))
                {
                    Card.CardGroupMaps.Add(this);
                }
                if (idCard != Card.idCard)
                {
                    idCard = Card.idCard;
                }
            }
        }
    
        private void FixupCardGroup(CardGroup previousValue)
        {
            if (previousValue != null && previousValue.CardGroupMaps.Contains(this))
            {
                previousValue.CardGroupMaps.Remove(this);
            }
    
            if (CardGroup != null)
            {
                if (!CardGroup.CardGroupMaps.Contains(this))
                {
                    CardGroup.CardGroupMaps.Add(this);
                }
                if (idCardGroup != CardGroup.idCardGroup)
                {
                    idCardGroup = CardGroup.idCardGroup;
                }
            }
        }

        #endregion
    }
}
