//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Collections.Specialized;

namespace TVDatabaseEntities
{
    public partial class Server
    {
        #region Primitive Properties
    
        public virtual int idServer
        {
            get;
            set;
        }
    
        public virtual bool isMaster
        {
            get;
            set;
        }
    
        public virtual string hostName
        {
            get;
            set;
        }
    
        public virtual int rtspPort
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<Card> Cards
        {
            get
            {
                if (_cards == null)
                {
                    var newCollection = new FixupCollection<Card>();
                    newCollection.CollectionChanged += FixupCards;
                    _cards = newCollection;
                }
                return _cards;
            }
            set
            {
                if (!ReferenceEquals(_cards, value))
                {
                    var previousValue = _cards as FixupCollection<Card>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupCards;
                    }
                    _cards = value;
                    var newValue = value as FixupCollection<Card>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupCards;
                    }
                }
            }
        }
        private ICollection<Card> _cards;

        #endregion
        #region Association Fixup
    
        private void FixupCards(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Card item in e.NewItems)
                {
                    item.Server = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Card item in e.OldItems)
                {
                    if (ReferenceEquals(item.Server, this))
                    {
                        item.Server = null;
                    }
                }
            }
        }

        #endregion
    }
}
