//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TVDatabaseEntities
{
    public partial class RadioGroupMap
    {
        #region Primitive Properties
    
        public virtual int idMap
        {
            get;
            set;
        }
    
        public virtual int idGroup
        {
            get { return _idGroup; }
            set
            {
                if (_idGroup != value)
                {
                    if (RadioChannelGroup != null && RadioChannelGroup.idGroup != value)
                    {
                        RadioChannelGroup = null;
                    }
                    _idGroup = value;
                }
            }
        }
        private int _idGroup;
    
        public virtual int idChannel
        {
            get { return _idChannel; }
            set
            {
                if (_idChannel != value)
                {
                    if (Channel != null && Channel.idChannel != value)
                    {
                        Channel = null;
                    }
                    _idChannel = value;
                }
            }
        }
        private int _idChannel;
    
        public virtual int SortOrder
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual RadioChannelGroup RadioChannelGroup
        {
            get { return _radioChannelGroup; }
            set
            {
                if (!ReferenceEquals(_radioChannelGroup, value))
                {
                    var previousValue = _radioChannelGroup;
                    _radioChannelGroup = value;
                    FixupRadioChannelGroup(previousValue);
                }
            }
        }
        private RadioChannelGroup _radioChannelGroup;
    
        public virtual Channel Channel
        {
            get { return _channel; }
            set
            {
                if (!ReferenceEquals(_channel, value))
                {
                    var previousValue = _channel;
                    _channel = value;
                    FixupChannel(previousValue);
                }
            }
        }
        private Channel _channel;

        #endregion
        #region Association Fixup
    
        private void FixupRadioChannelGroup(RadioChannelGroup previousValue)
        {
            if (previousValue != null && previousValue.RadioGroupMaps.Contains(this))
            {
                previousValue.RadioGroupMaps.Remove(this);
            }
    
            if (RadioChannelGroup != null)
            {
                if (!RadioChannelGroup.RadioGroupMaps.Contains(this))
                {
                    RadioChannelGroup.RadioGroupMaps.Add(this);
                }
                if (idGroup != RadioChannelGroup.idGroup)
                {
                    idGroup = RadioChannelGroup.idGroup;
                }
            }
        }
    
        private void FixupChannel(Channel previousValue)
        {
            if (previousValue != null && previousValue.RadioGroupMaps.Contains(this))
            {
                previousValue.RadioGroupMaps.Remove(this);
            }
    
            if (Channel != null)
            {
                if (!Channel.RadioGroupMaps.Contains(this))
                {
                    Channel.RadioGroupMaps.Add(this);
                }
                if (idChannel != Channel.idChannel)
                {
                    idChannel = Channel.idChannel;
                }
            }
        }

        #endregion
    }
}
