//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TVDatabaseEntities
{
    public partial class RuleBasedSchedule
    {
        #region Primitive Properties
    
        public virtual int id_RuleBasedSchedule
        {
            get;
            set;
        }
    
        public virtual string scheduleName
        {
            get;
            set;
        }
    
        public virtual int maxAirings
        {
            get;
            set;
        }
    
        public virtual int priority
        {
            get;
            set;
        }
    
        public virtual string directory
        {
            get;
            set;
        }
    
        public virtual int quality
        {
            get;
            set;
        }
    
        public virtual int keepMethod
        {
            get;
            set;
        }
    
        public virtual System.DateTime keepDate
        {
            get;
            set;
        }
    
        public virtual int preRecordInterval
        {
            get;
            set;
        }
    
        public virtual int postRecordInterval
        {
            get;
            set;
        }
    
        public virtual string rules
        {
            get;
            set;
        }

        #endregion
    }
}
