/*
 *  Copyright (C) 2006-2008 Team MediaPortal
 *  http://www.team-mediaportal.com
 *
 *  This Program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2, or (at your option)
 *  any later version.
 *
 *  This Program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with GNU Make; see the file COPYING.  If not, write to
 *  the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
 *  http://www.gnu.org/copyleft/gpl.html
 *
 */
#pragma once
#include <map>
#include <vector>
#include "ICallBackTableParser.h"

using namespace std;


class ICallBackNitDvb : public ICallBackTableParser
{
  public:
    virtual ~ICallBackNitDvb() {}

    virtual void OnNitServiceReceived(unsigned char tableId,
                                      unsigned short tableIdExtension,
                                      unsigned short originalNetworkId,
                                      unsigned short transportStreamId,
                                      unsigned short serviceId,
                                      unsigned short freesatChannelId,
                                      unsigned short openTvChannelId,
                                      bool visibleInGuide,
                                      const map<unsigned long, unsigned short>& logicalChannelNumbers,
                                      const char* defaultAuthority,
                                      const vector<unsigned long>& availableInCells,
                                      const vector<unsigned long long>& targetRegionIds,
                                      const vector<unsigned short>& freesatRegionIds,
                                      const vector<unsigned short>& openTvRegionIds,
                                      const vector<unsigned short>& freesatChannelCategoryIds,
                                      const vector<unsigned char>& norDigChannelListIds,
                                      const vector<unsigned long>& availableInCountries,
                                      const vector<unsigned long>& unavailableInCountries) {}
    virtual void OnNitServiceChanged(unsigned char tableId,
                                      unsigned short tableIdExtension,
                                      unsigned short originalNetworkId,
                                      unsigned short transportStreamId,
                                      unsigned short serviceId,
                                      unsigned short freesatChannelId,
                                      unsigned short openTvChannelId,
                                      bool visibleInGuide,
                                      const map<unsigned long, unsigned short>& logicalChannelNumbers,
                                      const char* defaultAuthority,
                                      const vector<unsigned long>& availableInCells,
                                      const vector<unsigned long long>& targetRegionIds,
                                      const vector<unsigned short>& freesatRegionIds,
                                      const vector<unsigned short>& openTvRegionIds,
                                      const vector<unsigned short>& freesatChannelCategoryIds,
                                      const vector<unsigned char>& norDigChannelListIds,
                                      const vector<unsigned long>& availableInCountries,
                                      const vector<unsigned long>& unavailableInCountries) {}
    virtual void OnNitServiceRemoved(unsigned char tableId,
                                      unsigned short tableIdExtension,
                                      unsigned short originalNetworkId,
                                      unsigned short transportStreamId,
                                      unsigned short serviceId,
                                      unsigned short freesatChannelId,
                                      unsigned short openTvChannelId,
                                      bool visibleInGuide,
                                      const map<unsigned long, unsigned short>& logicalChannelNumbers,
                                      const char* defaultAuthority,
                                      const vector<unsigned long>& availableInCells,
                                      const vector<unsigned long long>& targetRegionIds,
                                      const vector<unsigned short>& freesatRegionIds,
                                      const vector<unsigned short>& openTvRegionIds,
                                      const vector<unsigned short>& freesatChannelCategoryIds,
                                      const vector<unsigned char>& norDigChannelListIds,
                                      const vector<unsigned long>& availableInCountries,
                                      const vector<unsigned long>& unavailableInCountries) {}

    virtual void OnNitTransmitterCableReceived(unsigned char tableId,
                                                unsigned short networkId,
                                                unsigned short originalNetworkId,
                                                unsigned short transportStreamId,
                                                bool isHomeTransmitter,
                                                const vector<unsigned long>& frequencies,
                                                unsigned char outerFecMethod,
                                                unsigned char modulation,
                                                unsigned long symbolRate,
                                                unsigned char innerFecRate,
                                                bool isC2,
                                                unsigned char plpId,
                                                unsigned char dataSliceId,
                                                unsigned char frequencyType,
                                                unsigned char activeOfdmSymbolDuration,
                                                unsigned char guardInterval) {}
    virtual void OnNitTransmitterCableChanged(unsigned char tableId,
                                                unsigned short networkId,
                                                unsigned short originalNetworkId,
                                                unsigned short transportStreamId,
                                                bool isHomeTransmitter,
                                                const vector<unsigned long>& frequencies,
                                                unsigned char outerFecMethod,
                                                unsigned char modulation,
                                                unsigned long symbolRate,
                                                unsigned char innerFecRate,
                                                bool isC2,
                                                unsigned char plpId,
                                                unsigned char dataSliceId,
                                                unsigned char frequencyType,
                                                unsigned char activeOfdmSymbolDuration,
                                                unsigned char guardInterval) {}
    virtual void OnNitTransmitterCableRemoved(unsigned char tableId,
                                                unsigned short networkId,
                                                unsigned short originalNetworkId,
                                                unsigned short transportStreamId,
                                                bool isHomeTransmitter,
                                                const vector<unsigned long>& frequencies,
                                                unsigned char outerFecMethod,
                                                unsigned char modulation,
                                                unsigned long symbolRate,
                                                unsigned char innerFecRate,
                                                bool isC2,
                                                unsigned char plpId,
                                                unsigned char dataSliceId,
                                                unsigned char frequencyType,
                                                unsigned char activeOfdmSymbolDuration,
                                                unsigned char guardInterval) {}

    virtual void OnNitTransmitterSatelliteReceived(unsigned char tableId,
                                                    unsigned short networkId,
                                                    unsigned short originalNetworkId,
                                                    unsigned short transportStreamId,
                                                    bool isHomeTransmitter,
                                                    const vector<unsigned long>& frequencies,
                                                    unsigned short orbitalPosition,
                                                    bool westEastFlag,
                                                    unsigned char polarisation,
                                                    unsigned char modulation,
                                                    unsigned long symbolRate,
                                                    unsigned char innerFecRate,
                                                    unsigned char rollOff,
                                                    bool isS2,
                                                    bool multipleInputStreamFlag,
                                                    bool backwardsCompatibilityIndicator,
                                                    unsigned long scramblingSequenceIndex,
                                                    unsigned char inputStreamIdentifier) {}
    virtual void OnNitTransmitterSatelliteChanged(unsigned char tableId,
                                                    unsigned short networkId,
                                                    unsigned short originalNetworkId,
                                                    unsigned short transportStreamId,
                                                    bool isHomeTransmitter,
                                                    const vector<unsigned long>& frequencies,
                                                    unsigned short orbitalPosition,
                                                    bool westEastFlag,
                                                    unsigned char polarisation,
                                                    unsigned char modulation,
                                                    unsigned long symbolRate,
                                                    unsigned char innerFecRate,
                                                    unsigned char rollOff,
                                                    bool isS2,
                                                    bool multipleInputStreamFlag,
                                                    bool backwardsCompatibilityIndicator,
                                                    unsigned long scramblingSequenceIndex,
                                                    unsigned char inputStreamIdentifier) {}
    virtual void OnNitTransmitterSatelliteRemoved(unsigned char tableId,
                                                    unsigned short networkId,
                                                    unsigned short originalNetworkId,
                                                    unsigned short transportStreamId,
                                                    bool isHomeTransmitter,
                                                    const vector<unsigned long>& frequencies,
                                                    unsigned short orbitalPosition,
                                                    bool westEastFlag,
                                                    unsigned char polarisation,
                                                    unsigned char modulation,
                                                    unsigned long symbolRate,
                                                    unsigned char innerFecRate,
                                                    unsigned char rollOff,
                                                    bool isS2,
                                                    bool multipleInputStreamFlag,
                                                    bool backwardsCompatibilityIndicator,
                                                    unsigned long scramblingSequenceIndex,
                                                    unsigned char inputStreamIdentifier) {}

    virtual void OnNitTransmitterTerrestrialReceived(unsigned char tableId,
                                                      unsigned short networkId,
                                                      unsigned short originalNetworkId,
                                                      unsigned short transportStreamId,
                                                      bool isHomeTransmitter,
                                                      const vector<unsigned long>& frequencies,
                                                      unsigned short bandwidth,
                                                      bool isHighPriority,
                                                      bool timeSlicingIndicator,
                                                      bool mpeFecIndicator,
                                                      unsigned char constellation,
                                                      bool indepthInterleaverUsed,
                                                      unsigned char hierarchyAlpha,
                                                      unsigned char codeRateHpStream,
                                                      unsigned char codeRateLpStream,
                                                      unsigned char guardInterval,
                                                      unsigned char transmissionMode,
                                                      bool otherFrequencyFlag,
                                                      bool isT2,
                                                      unsigned char plpId,
                                                      unsigned short t2SystemId,
                                                      bool multipleInputStreamFlag,
                                                      bool timeFrequencySlicingFlag,
                                                      unsigned short cellId,
                                                      unsigned char cellIdExtension) {}
    virtual void OnNitTransmitterTerrestrialChanged(unsigned char tableId,
                                                      unsigned short networkId,
                                                      unsigned short originalNetworkId,
                                                      unsigned short transportStreamId,
                                                      bool isHomeTransmitter,
                                                      const vector<unsigned long>& frequencies,
                                                      unsigned short bandwidth,
                                                      bool isHighPriority,
                                                      bool timeSlicingIndicator,
                                                      bool mpeFecIndicator,
                                                      unsigned char constellation,
                                                      bool indepthInterleaverUsed,
                                                      unsigned char hierarchyAlpha,
                                                      unsigned char codeRateHpStream,
                                                      unsigned char codeRateLpStream,
                                                      unsigned char guardInterval,
                                                      unsigned char transmissionMode,
                                                      bool otherFrequencyFlag,
                                                      bool isT2,
                                                      unsigned char plpId,
                                                      unsigned short t2SystemId,
                                                      bool multipleInputStreamFlag,
                                                      bool timeFrequencySlicingFlag,
                                                      unsigned short cellId,
                                                      unsigned char cellIdExtension) {}
    virtual void OnNitTransmitterTerrestrialRemoved(unsigned char tableId,
                                                      unsigned short networkId,
                                                      unsigned short originalNetworkId,
                                                      unsigned short transportStreamId,
                                                      bool isHomeTransmitter,
                                                      const vector<unsigned long>& frequencies,
                                                      unsigned short bandwidth,
                                                      bool isHighPriority,
                                                      bool timeSlicingIndicator,
                                                      bool mpeFecIndicator,
                                                      unsigned char constellation,
                                                      bool indepthInterleaverUsed,
                                                      unsigned char hierarchyAlpha,
                                                      unsigned char codeRateHpStream,
                                                      unsigned char codeRateLpStream,
                                                      unsigned char guardInterval,
                                                      unsigned char transmissionMode,
                                                      bool otherFrequencyFlag,
                                                      bool isT2,
                                                      unsigned char plpId,
                                                      unsigned short t2SystemId,
                                                      bool multipleInputStreamFlag,
                                                      bool timeFrequencySlicingFlag,
                                                      unsigned short cellId,
                                                      unsigned char cellIdExtension) {}
};