/* 
 *	Copyright (C) 2006-2008 Team MediaPortal
 *	http://www.team-mediaportal.com
 *
 *  This Program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2, or (at your option)
 *  any later version.
 *   
 *  This Program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *  GNU General Public License for more details.
 *   
 *  You should have received a copy of the GNU General Public License
 *  along with GNU Make; see the file COPYING.  If not, write to
 *  the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA. 
 *  http://www.gnu.org/copyleft/gpl.html
 *
 */

char* ukThemes[] = 
{
"No Category",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Shopping",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Children",
"Children - Cartoons",
"Children - Comedy",
"Children - Drama",
"Children - Educational",
"Children - Under 5",
"Children - Factual",
"Children - Magazine",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Entertainment",
"Entertainment - Action",
"Entertainment - Comedy",
"Entertainment - Detective",
"Entertainment - Drama",
"Entertainment - Game Show",
"Entertainment - Sci-FI",
"Entertainment - Soap",
"Entertainment - Animation",
"Entertainment - Chat Show",
"Entertainment - Cooking",
"Entertainment - Factual",
"Entertainment - Fashion",
"Entertainment - Gardening",
"Entertainment - Travel",
"Entertainment - Technology",
"Entertainment - Arts",
"Entertainment - Lifestyle",
"Entertainment - Home",
"Entertainment - Magazine",
"Entertainment - Medical",
"Entertainment - Review",
"Entertainment - Antiques",
"Entertainment - Motors",
"Entertainment - Art&Lit",
"Entertainment - Ballet",
"Entertainment - Opera",
"",
"",
"",
"",
"",
"Music",
"Music - Classical ",
"Music - Folk and Country",
"Music - National Music",
"Music - Jazz",
"Music - Opera",
"Music - Rock&Pop",
"Music - Alternative Music",
"Music - Events",
"Music - Club and Dance",
"Music - Hip Hop",
"Music - Soul/R&B",
"Music - Dance",
"",
"",
"",
"Music - Features",
"",
"",
"",
"",
"Music - Lifestyle",
"Music - News and Weather",
"Music - Easy Listening",
"Music - Discussion",
"Music - Entertainment",
"Music - Religious",
"",
"",
"",
"",
"",
"News & Documentaries",
"News & Documentaries - Business",
"News & Documentaries - World Cultures",
"News & Documentaries - Adventure",
"News & Documentaries - Biography",
"News & Documentaries - Educational",
"News & Documentaries - Feature",
"News & Documentaries - Politics",
"News & Documentaries - News",
"News & Documentaries - Nature",
"News & Documentaries - Religious",
"News & Documentaries - Science",
"News & Documentaries - Showbiz",
"News & Documentaries - War Documentary",
"News & Documentaries - Historical",
"News & Documentaries - Ancient",
"News & Documentaries - Transport",
"News & Documentaries - Docudrama",
"News & Documentaries - World Affairs",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Movie",
"Movie - Action",
"Movie - Animation",
"",
"Movie - Comedy",
"Movie - Family",
"Movie - Drama",
"",
"Movie - Sci-Fi",
"Movie - Thriller",
"Movie - Horror",
"Movie - Romance",
"Movie - Musical",
"Movie - Mystery",
"Movie - Western",
"Movie - Factual",
"Movie - Fantasy",
"Movie - Erotic",
"Movie - Adventure",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Sports - Other",
"Sports - American Football",
"Sports - Athletics",
"Sports - Baseball",
"Sports - Basketball",
"Sports - Boxing",
"Sports - Cricket",
"Sports - Fishing",
"Sports - Football",
"Sports - Golf",
"Sports - Ice Hockey",
"Sports - Motor Sport",
"Sports - Racing",
"Sports - Rugby",
"Sports - Equestrian",
"Sports - Winter Sports",
"Sports - Snooker / Pool",
"Sports - Tennis",
"Sports - Wrestling",
"Sports - Darts",
"Sports - Watersports",
"Sports - Extreme",
"",
"",
"",
"",
"",
"",
"",
"",
"",
""
};


char* itThemes[] = 
{
"Non Definito",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Intrattenimento",
"Intrattenimento - Fiction",
"Intrattenimento - Sit Com",
"Intrattenimento - Show",
"Intrattenimento - Telefilm",
"Intrattenimento - Soap Opera",
"Intrattenimento - Telenovela",
"Intrattenimento - Fantascienza",
"Intrattenimento - Animazione",
"Intrattenimento - Giallo",
"Intrattenimento - Drammatico",
"Intrattenimento - Romantico",
"Intrattenimento - Miniserie",
"Intrattenimento - Spettacolo",
"Intrattenimento - Quiz",
"Intrattenimento - Talk Show",
"Intrattenimento - Varietà",
"Intrattenimento - Festival",
"Intrattenimento - Teatro",
"Intrattenimento - Gioco",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Sport",
"Sport - Calcio",
"Sport - Tennis",
"Sport - Motori",
"Sport - Altri",
"Sport - Baseball",
"Sport - Ciclismo",
"Sport - Rugby",
"Sport - Basket",
"Sport - Boxe",
"Sport - Atletica",
"Sport - Football USA",
"Sport - Hockey",
"Sport - Sci",
"Sport - Equestri",
"Sport - Golf",
"Sport - Nuoto",
"Sport - Wrestling",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Film",
"Film - Drammatico",
"Film - Commedia",
"Film - Romantico",
"Film - Azione",
"Film - Fantascienza",
"Film - Western",
"Film - Comico",
"Film - Fantastico",
"Film - Avventura",
"Film - Poliziesco",
"Film - Guerra",
"Film - Horror",
"Film - Animazione",
"Film - Thriller",
"Film - Musicale",
"Film - Corto",
"Film - Cortometraggio",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Mondo e Tendenze",
"Mondo e Tendenze - Natura",
"Mondo e Tendenze - Arte e Cultura",
"Mondo e Tendenze - Lifestyle",
"Mondo e Tendenze - Viaggi",
"Mondo e Tendenze - Documentario",
"Mondo e Tendenze - Società",
"Mondo e Tendenze - Scienza",
"Mondo e Tendenze - Storia",
"Mondo e Tendenze - Sport",
"Mondo e Tendenze - Pesca",
"Mondo e Tendenze - Popoli",
"Mondo e Tendenze - Cinema",
"Mondo e Tendenze - Musica",
"Mondo e Tendenze - Hobby",
"Mondo e Tendenze - Caccia",
"Mondo e Tendenze - Reportage",
"Mondo e Tendenze - Magazine",
"Mondo e Tendenze - Magazine Cultura",
"Mondo e Tendenze - Magazine Scienza",
"Mondo e Tendenze - Politica",
"Mondo e Tendenze - Magazine Cinema",
"Mondo e Tendenze - Magazine Sport",
"Mondo e Tendenze - Attualità",
"Mondo e Tendenze - Moda",
"Mondo e Tendenze - Economia",
"Mondo e Tendenze - Magazine Caccia e Pesca",
"Mondo e Tendenze - Magazine Viaggi",
"Mondo e Tendenze - Magazine Natura",
"Mondo e Tendenze - Magazine Musica",
"Mondo e Tendenze - Religione",
"Mondo e Tendenze - Televendita",
"Informazione",
"Informazione - Notiziario",
"Informazione - Sport",
"Informazione - Economia",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Ragazzi e Musica",
"Ragazzi e Musica - Bambini",
"Ragazzi e Musica - Ragazzi",
"Ragazzi e Musica - Cartoni Animati",
"Ragazzi e Musica - Musica",
"Ragazzi e Musica - Film Animazione",
"Ragazzi e Musica - Film",
"Ragazzi e Musica - Telefilm",
"Ragazzi e Musica - Magazine",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Ragazzi e Musica - Danza",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"Altri Programmi",
"Altri Programmi - Educational",
"Altri Programmi - Regionale",
"Altri Programmi - Shopping",
"",
"Altri Programmi - Inizio e Fine Trasmissioni",
"Altri Programmi - Eventi Speciali",
"Altri Programmi - Film per Adulti",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
"",
""
};
