//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace Mediaportal.TV.Server.TVDatabase.Entities
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Channel))]
    [KnownType(typeof(ProgramCategory))]
    [KnownType(typeof(ProgramCredit))]
    public partial class Program: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public int IdProgram
        {
            get { return _idProgram; }
            set
            {
                if (_idProgram != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'IdProgram' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _idProgram = value;
                    OnPropertyChanged("IdProgram");
                }
            }
        }
        private int _idProgram;
    
        [DataMember]
        public int IdChannel
        {
            get { return _idChannel; }
            set
            {
                if (_idChannel != value)
                {
                    ChangeTracker.RecordOriginalValue("IdChannel", _idChannel);
                    if (!IsDeserializing)
                    {
                        if (Channel != null && Channel.IdChannel != value)
                        {
                            Channel = null;
                        }
                    }
                    _idChannel = value;
                    OnPropertyChanged("IdChannel");
                }
            }
        }
        private int _idChannel;
    
        [DataMember]
        public System.DateTime StartTime
        {
            get { return _startTime; }
            set
            {
                if (_startTime != value)
                {
                    _startTime = value;
                    OnPropertyChanged("StartTime");
                }
            }
        }
        private System.DateTime _startTime;
    
        [DataMember]
        public System.DateTime EndTime
        {
            get { return _endTime; }
            set
            {
                if (_endTime != value)
                {
                    _endTime = value;
                    OnPropertyChanged("EndTime");
                }
            }
        }
        private System.DateTime _endTime;
    
        [DataMember]
        public string Title
        {
            get { return _title; }
            set
            {
                if (_title != value)
                {
                    _title = value;
                    OnPropertyChanged("Title");
                }
            }
        }
        private string _title;
    
        [DataMember]
        public string Description
        {
            get { return _description; }
            set
            {
                if (_description != value)
                {
                    _description = value;
                    OnPropertyChanged("Description");
                }
            }
        }
        private string _description;
    
        [DataMember]
        public string EpisodeName
        {
            get { return _episodeName; }
            set
            {
                if (_episodeName != value)
                {
                    _episodeName = value;
                    OnPropertyChanged("EpisodeName");
                }
            }
        }
        private string _episodeName;
    
        [DataMember]
        public string SeriesId
        {
            get { return _seriesId; }
            set
            {
                if (_seriesId != value)
                {
                    _seriesId = value;
                    OnPropertyChanged("SeriesId");
                }
            }
        }
        private string _seriesId;
    
        [DataMember]
        public Nullable<int> SeasonNumber
        {
            get { return _seasonNumber; }
            set
            {
                if (_seasonNumber != value)
                {
                    _seasonNumber = value;
                    OnPropertyChanged("SeasonNumber");
                }
            }
        }
        private Nullable<int> _seasonNumber;
    
        [DataMember]
        public string EpisodeId
        {
            get { return _episodeId; }
            set
            {
                if (_episodeId != value)
                {
                    _episodeId = value;
                    OnPropertyChanged("EpisodeId");
                }
            }
        }
        private string _episodeId;
    
        [DataMember]
        public Nullable<int> EpisodeNumber
        {
            get { return _episodeNumber; }
            set
            {
                if (_episodeNumber != value)
                {
                    _episodeNumber = value;
                    OnPropertyChanged("EpisodeNumber");
                }
            }
        }
        private Nullable<int> _episodeNumber;
    
        [DataMember]
        public Nullable<int> EpisodePartNumber
        {
            get { return _episodePartNumber; }
            set
            {
                if (_episodePartNumber != value)
                {
                    _episodePartNumber = value;
                    OnPropertyChanged("EpisodePartNumber");
                }
            }
        }
        private Nullable<int> _episodePartNumber;
    
        [DataMember]
        public Nullable<bool> IsPreviouslyShown
        {
            get { return _isPreviouslyShown; }
            set
            {
                if (_isPreviouslyShown != value)
                {
                    _isPreviouslyShown = value;
                    OnPropertyChanged("IsPreviouslyShown");
                }
            }
        }
        private Nullable<bool> _isPreviouslyShown;
    
        [DataMember]
        public Nullable<System.DateTime> OriginalAirDate
        {
            get { return _originalAirDate; }
            set
            {
                if (_originalAirDate != value)
                {
                    _originalAirDate = value;
                    OnPropertyChanged("OriginalAirDate");
                }
            }
        }
        private Nullable<System.DateTime> _originalAirDate;
    
        [DataMember]
        public Nullable<int> IdProgramCategory
        {
            get { return _idProgramCategory; }
            set
            {
                if (_idProgramCategory != value)
                {
                    ChangeTracker.RecordOriginalValue("IdProgramCategory", _idProgramCategory);
                    if (!IsDeserializing)
                    {
                        if (ProgramCategory != null && ProgramCategory.IdProgramCategory != value)
                        {
                            ProgramCategory = null;
                        }
                    }
                    _idProgramCategory = value;
                    OnPropertyChanged("IdProgramCategory");
                }
            }
        }
        private Nullable<int> _idProgramCategory;
    
        [DataMember]
        public string Classification
        {
            get { return _classification; }
            set
            {
                if (_classification != value)
                {
                    _classification = value;
                    OnPropertyChanged("Classification");
                }
            }
        }
        private string _classification;
    
        [DataMember]
        public int Advisories
        {
            get { return _advisories; }
            set
            {
                if (_advisories != value)
                {
                    _advisories = value;
                    OnPropertyChanged("Advisories");
                }
            }
        }
        private int _advisories;
    
        [DataMember]
        public Nullable<bool> IsHighDefinition
        {
            get { return _isHighDefinition; }
            set
            {
                if (_isHighDefinition != value)
                {
                    _isHighDefinition = value;
                    OnPropertyChanged("IsHighDefinition");
                }
            }
        }
        private Nullable<bool> _isHighDefinition;
    
        [DataMember]
        public Nullable<bool> IsThreeDimensional
        {
            get { return _isThreeDimensional; }
            set
            {
                if (_isThreeDimensional != value)
                {
                    _isThreeDimensional = value;
                    OnPropertyChanged("IsThreeDimensional");
                }
            }
        }
        private Nullable<bool> _isThreeDimensional;
    
        [DataMember]
        public string AudioLanguages
        {
            get { return _audioLanguages; }
            set
            {
                if (_audioLanguages != value)
                {
                    _audioLanguages = value;
                    OnPropertyChanged("AudioLanguages");
                }
            }
        }
        private string _audioLanguages;
    
        [DataMember]
        public string SubtitlesLanguages
        {
            get { return _subtitlesLanguages; }
            set
            {
                if (_subtitlesLanguages != value)
                {
                    _subtitlesLanguages = value;
                    OnPropertyChanged("SubtitlesLanguages");
                }
            }
        }
        private string _subtitlesLanguages;
    
        [DataMember]
        public Nullable<bool> IsLive
        {
            get { return _isLive; }
            set
            {
                if (_isLive != value)
                {
                    _isLive = value;
                    OnPropertyChanged("IsLive");
                }
            }
        }
        private Nullable<bool> _isLive;
    
        [DataMember]
        public Nullable<int> ProductionYear
        {
            get { return _productionYear; }
            set
            {
                if (_productionYear != value)
                {
                    _productionYear = value;
                    OnPropertyChanged("ProductionYear");
                }
            }
        }
        private Nullable<int> _productionYear;
    
        [DataMember]
        public string ProductionCountry
        {
            get { return _productionCountry; }
            set
            {
                if (_productionCountry != value)
                {
                    _productionCountry = value;
                    OnPropertyChanged("ProductionCountry");
                }
            }
        }
        private string _productionCountry;
    
        [DataMember]
        public Nullable<decimal> StarRating
        {
            get { return _starRating; }
            set
            {
                if (_starRating != value)
                {
                    _starRating = value;
                    OnPropertyChanged("StarRating");
                }
            }
        }
        private Nullable<decimal> _starRating;
    
        [DataMember]
        public Nullable<decimal> StarRatingMaximum
        {
            get { return _starRatingMaximum; }
            set
            {
                if (_starRatingMaximum != value)
                {
                    _starRatingMaximum = value;
                    OnPropertyChanged("StarRatingMaximum");
                }
            }
        }
        private Nullable<decimal> _starRatingMaximum;
    
        [DataMember]
        public int State
        {
            get { return _state; }
            set
            {
                if (_state != value)
                {
                    _state = value;
                    OnPropertyChanged("State");
                }
            }
        }
        private int _state;
    
        [DataMember]
        public short StartTimeDayOfWeek
        {
            get { return _startTimeDayOfWeek; }
            set
            {
                if (_startTimeDayOfWeek != value)
                {
                    _startTimeDayOfWeek = value;
                    OnPropertyChanged("StartTimeDayOfWeek");
                }
            }
        }
        private short _startTimeDayOfWeek;
    
        [DataMember]
        public short EndTimeDayOfWeek
        {
            get { return _endTimeDayOfWeek; }
            set
            {
                if (_endTimeDayOfWeek != value)
                {
                    _endTimeDayOfWeek = value;
                    OnPropertyChanged("EndTimeDayOfWeek");
                }
            }
        }
        private short _endTimeDayOfWeek;
    
        [DataMember]
        public System.DateTime EndTimeOffset
        {
            get { return _endTimeOffset; }
            set
            {
                if (_endTimeOffset != value)
                {
                    _endTimeOffset = value;
                    OnPropertyChanged("EndTimeOffset");
                }
            }
        }
        private System.DateTime _endTimeOffset;
    
        [DataMember]
        public System.DateTime StartTimeOffset
        {
            get { return _startTimeOffset; }
            set
            {
                if (_startTimeOffset != value)
                {
                    _startTimeOffset = value;
                    OnPropertyChanged("StartTimeOffset");
                }
            }
        }
        private System.DateTime _startTimeOffset;

        #endregion
        #region Navigation Properties
    
        [DataMember]
        public Channel Channel
        {
            get { return _channel; }
            set
            {
                if (!ReferenceEquals(_channel, value))
                {
                    var previousValue = _channel;
                    _channel = value;
                    FixupChannel(previousValue);
                    OnNavigationPropertyChanged("Channel");
                }
            }
        }
        private Channel _channel;
    
        [DataMember]
        public ProgramCategory ProgramCategory
        {
            get { return _programCategory; }
            set
            {
                if (!ReferenceEquals(_programCategory, value))
                {
                    var previousValue = _programCategory;
                    _programCategory = value;
                    FixupProgramCategory(previousValue);
                    OnNavigationPropertyChanged("ProgramCategory");
                }
            }
        }
        private ProgramCategory _programCategory;
    
        [DataMember]
        public TrackableCollection<ProgramCredit> ProgramCredits
        {
            get
            {
                if (_programCredits == null)
                {
                    _programCredits = new TrackableCollection<ProgramCredit>();
                    _programCredits.CollectionChanged += FixupProgramCredits;
                }
                return _programCredits;
            }
            set
            {
                if (!ReferenceEquals(_programCredits, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_programCredits != null)
                    {
                        _programCredits.CollectionChanged -= FixupProgramCredits;
                        // This is the principal end in an association that performs cascade deletes.
                        // Remove the cascade delete event handler for any entities in the current collection.
                        foreach (ProgramCredit item in _programCredits)
                        {
                            ChangeTracker.ObjectStateChanging -= item.HandleCascadeDelete;
                        }
                    }
                    _programCredits = value;
                    if (_programCredits != null)
                    {
                        _programCredits.CollectionChanged += FixupProgramCredits;
                        // This is the principal end in an association that performs cascade deletes.
                        // Add the cascade delete event handler for any entities that are already in the new collection.
                        foreach (ProgramCredit item in _programCredits)
                        {
                            ChangeTracker.ObjectStateChanging += item.HandleCascadeDelete;
                        }
                    }
                    OnNavigationPropertyChanged("ProgramCredits");
                }
            }
        }
        private TrackableCollection<ProgramCredit> _programCredits;

        #endregion
        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        // This entity type is the dependent end in at least one association that performs cascade deletes.
        // This event handler will process notifications that occur when the principal end is deleted.
        internal void HandleCascadeDelete(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                this.MarkAsDeleted();
            }
        }
    
        protected virtual void ClearNavigationProperties()
        {
            Channel = null;
            ProgramCategory = null;
            ProgramCredits.Clear();
        }

        #endregion
        #region Association Fixup
    
        private void FixupChannel(Channel previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.Programs.Contains(this))
            {
                previousValue.Programs.Remove(this);
            }
    
            if (Channel != null)
            {
                if (!Channel.Programs.Contains(this))
                {
                    Channel.Programs.Add(this);
                }
    
                IdChannel = Channel.IdChannel;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("Channel")
                    && (ChangeTracker.OriginalValues["Channel"] == Channel))
                {
                    ChangeTracker.OriginalValues.Remove("Channel");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("Channel", previousValue);
                }
                if (Channel != null && !Channel.ChangeTracker.ChangeTrackingEnabled)
                {
                    Channel.StartTracking();
                }
            }
        }
    
        private void FixupProgramCategory(ProgramCategory previousValue, bool skipKeys = false)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.Programs.Contains(this))
            {
                previousValue.Programs.Remove(this);
            }
    
            if (ProgramCategory != null)
            {
                if (!ProgramCategory.Programs.Contains(this))
                {
                    ProgramCategory.Programs.Add(this);
                }
    
                IdProgramCategory = ProgramCategory.IdProgramCategory;
            }
            else if (!skipKeys)
            {
                IdProgramCategory = null;
            }
    
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("ProgramCategory")
                    && (ChangeTracker.OriginalValues["ProgramCategory"] == ProgramCategory))
                {
                    ChangeTracker.OriginalValues.Remove("ProgramCategory");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("ProgramCategory", previousValue);
                }
                if (ProgramCategory != null && !ProgramCategory.ChangeTracker.ChangeTrackingEnabled)
                {
                    ProgramCategory.StartTracking();
                }
            }
        }
    
        private void FixupProgramCredits(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (ProgramCredit item in e.NewItems)
                {
                    item.Program = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("ProgramCredits", item);
                    }
                    // This is the principal end in an association that performs cascade deletes.
                    // Update the event listener to refer to the new dependent.
                    ChangeTracker.ObjectStateChanging += item.HandleCascadeDelete;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (ProgramCredit item in e.OldItems)
                {
                    if (ReferenceEquals(item.Program, this))
                    {
                        item.Program = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("ProgramCredits", item);
                    }
                    // This is the principal end in an association that performs cascade deletes.
                    // Remove the previous dependent from the event listener.
                    ChangeTracker.ObjectStateChanging -= item.HandleCascadeDelete;
                }
            }
        }

        #endregion
    }
}
