//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace Mediaportal.TV.Server.TVDatabase.Entities
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(ServiceAtsc))]
    [KnownType(typeof(ServiceDvb))]
    public partial class ServiceMpeg2 : ServiceDetail, IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public Nullable<int> TransportStreamId
        {
            get { return _transportStreamId; }
            set
            {
                if (_transportStreamId != value)
                {
                    _transportStreamId = value;
                    OnPropertyChanged("TransportStreamId");
                }
            }
        }
        private Nullable<int> _transportStreamId;
    
        [DataMember]
        public Nullable<int> ServiceId
        {
            get { return _serviceId; }
            set
            {
                if (_serviceId != value)
                {
                    _serviceId = value;
                    OnPropertyChanged("ServiceId");
                }
            }
        }
        private Nullable<int> _serviceId;
    
        [DataMember]
        public Nullable<int> PmtPid
        {
            get { return _pmtPid; }
            set
            {
                if (_pmtPid != value)
                {
                    _pmtPid = value;
                    OnPropertyChanged("PmtPid");
                }
            }
        }
        private Nullable<int> _pmtPid;

        #endregion
        #region ChangeTracking
    
        protected override void ClearNavigationProperties()
        {
            base.ClearNavigationProperties();
        }

        #endregion
    }
}
