//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace Mediaportal.TV.Server.TVDatabase.Entities
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Tuner))]
    [KnownType(typeof(Satellite))]
    [KnownType(typeof(LnbType))]
    public partial class TunerSatellite: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public int IdTunerSatellite
        {
            get { return _idTunerSatellite; }
            set
            {
                if (_idTunerSatellite != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'IdTunerSatellite' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _idTunerSatellite = value;
                    OnPropertyChanged("IdTunerSatellite");
                }
            }
        }
        private int _idTunerSatellite;
    
        [DataMember]
        public int IdSatellite
        {
            get { return _idSatellite; }
            set
            {
                if (_idSatellite != value)
                {
                    ChangeTracker.RecordOriginalValue("IdSatellite", _idSatellite);
                    if (!IsDeserializing)
                    {
                        if (Satellite != null && Satellite.IdSatellite != value)
                        {
                            Satellite = null;
                        }
                    }
                    _idSatellite = value;
                    OnPropertyChanged("IdSatellite");
                }
            }
        }
        private int _idSatellite;
    
        [DataMember]
        public Nullable<int> IdTuner
        {
            get { return _idTuner; }
            set
            {
                if (_idTuner != value)
                {
                    ChangeTracker.RecordOriginalValue("IdTuner", _idTuner);
                    if (!IsDeserializing)
                    {
                        if (Tuner != null && Tuner.IdTuner != value)
                        {
                            Tuner = null;
                        }
                    }
                    _idTuner = value;
                    OnPropertyChanged("IdTuner");
                }
            }
        }
        private Nullable<int> _idTuner;
    
        [DataMember]
        public int IdLnbType
        {
            get { return _idLnbType; }
            set
            {
                if (_idLnbType != value)
                {
                    ChangeTracker.RecordOriginalValue("IdLnbType", _idLnbType);
                    if (!IsDeserializing)
                    {
                        if (LnbType != null && LnbType.IdLnbType != value)
                        {
                            LnbType = null;
                        }
                    }
                    _idLnbType = value;
                    OnPropertyChanged("IdLnbType");
                }
            }
        }
        private int _idLnbType;
    
        [DataMember]
        public int DiseqcPort
        {
            get { return _diseqcPort; }
            set
            {
                if (_diseqcPort != value)
                {
                    _diseqcPort = value;
                    OnPropertyChanged("DiseqcPort");
                }
            }
        }
        private int _diseqcPort;
    
        [DataMember]
        public int DiseqcMotorPosition
        {
            get { return _diseqcMotorPosition; }
            set
            {
                if (_diseqcMotorPosition != value)
                {
                    _diseqcMotorPosition = value;
                    OnPropertyChanged("DiseqcMotorPosition");
                }
            }
        }
        private int _diseqcMotorPosition;
    
        [DataMember]
        public int Tone22kState
        {
            get { return _tone22kState; }
            set
            {
                if (_tone22kState != value)
                {
                    _tone22kState = value;
                    OnPropertyChanged("Tone22kState");
                }
            }
        }
        private int _tone22kState;
    
        [DataMember]
        public int ToneBurst
        {
            get { return _toneBurst; }
            set
            {
                if (_toneBurst != value)
                {
                    _toneBurst = value;
                    OnPropertyChanged("ToneBurst");
                }
            }
        }
        private int _toneBurst;
    
        [DataMember]
        public bool IsToroidalDish
        {
            get { return _isToroidalDish; }
            set
            {
                if (_isToroidalDish != value)
                {
                    _isToroidalDish = value;
                    OnPropertyChanged("IsToroidalDish");
                }
            }
        }
        private bool _isToroidalDish;

        #endregion
        #region Navigation Properties
    
        [DataMember]
        public Tuner Tuner
        {
            get { return _tuner; }
            set
            {
                if (!ReferenceEquals(_tuner, value))
                {
                    var previousValue = _tuner;
                    _tuner = value;
                    FixupTuner(previousValue);
                    OnNavigationPropertyChanged("Tuner");
                }
            }
        }
        private Tuner _tuner;
    
        [DataMember]
        public Satellite Satellite
        {
            get { return _satellite; }
            set
            {
                if (!ReferenceEquals(_satellite, value))
                {
                    var previousValue = _satellite;
                    _satellite = value;
                    FixupSatellite(previousValue);
                    OnNavigationPropertyChanged("Satellite");
                }
            }
        }
        private Satellite _satellite;
    
        [DataMember]
        public LnbType LnbType
        {
            get { return _lnbType; }
            set
            {
                if (!ReferenceEquals(_lnbType, value))
                {
                    var previousValue = _lnbType;
                    _lnbType = value;
                    FixupLnbType(previousValue);
                    OnNavigationPropertyChanged("LnbType");
                }
            }
        }
        private LnbType _lnbType;

        #endregion
        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        // This entity type is the dependent end in at least one association that performs cascade deletes.
        // This event handler will process notifications that occur when the principal end is deleted.
        internal void HandleCascadeDelete(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                this.MarkAsDeleted();
            }
        }
    
        protected virtual void ClearNavigationProperties()
        {
            Tuner = null;
            Satellite = null;
            LnbType = null;
        }

        #endregion
        #region Association Fixup
    
        private void FixupTuner(Tuner previousValue, bool skipKeys = false)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.TunerSatellites.Contains(this))
            {
                previousValue.TunerSatellites.Remove(this);
            }
    
            if (Tuner != null)
            {
                if (!Tuner.TunerSatellites.Contains(this))
                {
                    Tuner.TunerSatellites.Add(this);
                }
    
                IdTuner = Tuner.IdTuner;
            }
            else if (!skipKeys)
            {
                IdTuner = null;
            }
    
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("Tuner")
                    && (ChangeTracker.OriginalValues["Tuner"] == Tuner))
                {
                    ChangeTracker.OriginalValues.Remove("Tuner");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("Tuner", previousValue);
                }
                if (Tuner != null && !Tuner.ChangeTracker.ChangeTrackingEnabled)
                {
                    Tuner.StartTracking();
                }
            }
        }
    
        private void FixupSatellite(Satellite previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.TunerSatellites.Contains(this))
            {
                previousValue.TunerSatellites.Remove(this);
            }
    
            if (Satellite != null)
            {
                if (!Satellite.TunerSatellites.Contains(this))
                {
                    Satellite.TunerSatellites.Add(this);
                }
    
                IdSatellite = Satellite.IdSatellite;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("Satellite")
                    && (ChangeTracker.OriginalValues["Satellite"] == Satellite))
                {
                    ChangeTracker.OriginalValues.Remove("Satellite");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("Satellite", previousValue);
                }
                if (Satellite != null && !Satellite.ChangeTracker.ChangeTrackingEnabled)
                {
                    Satellite.StartTracking();
                }
            }
        }
    
        private void FixupLnbType(LnbType previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.TunerSatellites.Contains(this))
            {
                previousValue.TunerSatellites.Remove(this);
            }
    
            if (LnbType != null)
            {
                if (!LnbType.TunerSatellites.Contains(this))
                {
                    LnbType.TunerSatellites.Add(this);
                }
    
                IdLnbType = LnbType.IdLnbType;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("LnbType")
                    && (ChangeTracker.OriginalValues["LnbType"] == LnbType))
                {
                    ChangeTracker.OriginalValues.Remove("LnbType");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("LnbType", previousValue);
                }
                if (LnbType != null && !LnbType.ChangeTracker.ChangeTrackingEnabled)
                {
                    LnbType.StartTracking();
                }
            }
        }

        #endregion
    }
}
