//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Mediaportal.TV.Server.TVDatabase.Entities
{
    public partial class Timespan
    {
        #region Primitive Properties
    
        public virtual int idTimespan
        {
            get;
            set;
        }
    
        public virtual System.DateTime startTime
        {
            get;
            set;
        }
    
        public virtual System.DateTime endTime
        {
            get;
            set;
        }
    
        public virtual int dayOfWeek
        {
            get;
            set;
        }
    
        public virtual int idKeyword
        {
            get;
            set;
        }

        #endregion
    }
}
