#include "stdafx.h"
#include "OpenTypeLangTags.h"

//contains 3 char codes from hb-ot-tag-table.hh and cleaned up descriptions.  duplicate langauges removed
//libass currently supports only two-letter codes, but harfbuzz supports more.
//libass will not find the language if it does not match the hbtag below, so only the 2-char codes work

OpenTypeLang::OpenTypeLangTag OpenTypeLang::OpenTypeLangTags[763] =
{
  {"aa", L"Afar"},
  {"aae", L"Arbëreshë Albanian"},
  {"aao", L"Algerian Saharan Arabic"},
  {"aat", L"Arvanitika Albanian"},
  {"ab", L"Abkhazian"},
  {"abh", L"Tajiki Arabic"},
  {"abq", L"Abaza"},
  {"abv", L"Baharna Arabic"},
  {"acf", L"Saint Lucian Creole French"},
  {"acm", L"Mesopotamian Arabic"},
  {"acq", L"Ta'izzi-Adeni Arabic"},
  {"acw", L"Hijazi Arabic"},
  {"acx", L"Omani Arabic"},
  {"acy", L"Cypriot Arabic"},
  {"ada", L"Adangme"},
  {"adf", L"Dhofari Arabic"},
  {"aeb", L"Tunisian Arabic"},
  {"aec", L"Saidi Arabic"},
  {"af", L"Afrikaans"},
  {"afb", L"Gulf Arabic"},
  {"ahg", L"Qimant"},
  {"aht", L"Ahtena"},
  {"aii", L"Assyrian Neo-Aramaic"},
  {"aiw", L"Aari"},
  {"ajp", L"South Levantine Arabic"},
  {"ak", L"Akan"},
  {"aln", L"Gheg Albanian"},
  {"als", L"Tosk Albanian"},
  {"am", L"Amharic"},
  {"amf", L"Hamer-Banna"},
  {"amw", L"Western Neo-Aramaic"},
  {"an", L"Aragonese"},
  {"apc", L"North Levantine Arabic"},
  {"apd", L"Sudanese Arabic"},
  {"apj", L"Jicarilla Apache"},
  {"apk", L"Kiowa Apache"},
  {"apl", L"Lipan Apache"},
  {"apm", L"Mescalero-Chiricahua Apache"},
  {"apw", L"Western Apache"},
  {"ar", L"Arabic"},
  {"arb", L"Standard Arabic"},
  {"arn", L"Mapudungun"},
  {"arq", L"Algerian Arabic"},
  {"ars", L"Najdi Arabic"},
  {"ary", L"Moroccan Arabic"},
  {"arz", L"Egyptian Arabic"},
  {"as", L"Assamese"},
  {"atj", L"Atikamekw"},
  {"atv", L"Northern Altai"},
  {"auz", L"Uzbeki Arabic"},
  {"av", L"Avaric"},
  {"avl", L"Eastern Egyptian Bedawi Arabic"},
  {"ay", L"Aymara"},
  {"ayc", L"Southern Aymara"},
  {"ayh", L"Hadrami Arabic"},
  {"ayl", L"Libyan Arabic"},
  {"ayn", L"Sanaani Arabic"},
  {"ayp", L"North Mesopotamian Arabic"},
  {"ayr", L"Central Aymara"},
  {"az", L"Azerbaijani"},
  {"azj", L"North Azerbaijani"},
  {"ba", L"Bashkir"},
  {"bad", L"Banda [family]"},
  {"bai", L"Bamileke [family]"},
  {"bal", L"Baluchi"},
  {"bbz", L"Babalia Creole Arabic"},
  {"bcc", L"Southern Balochi"},
  {"bci", L"Baoulé"},
  {"bcl", L"Central Bikol"},
  {"bcq", L"Bench"},
  {"bcr", L"Babine"},
  {"be", L"Belarusian"},
  {"bea", L"Beaver"},
  {"beb", L"Bebele"},
  {"ber", L"Berber [family]"},
  {"bfq", L"Badaga"},
  {"bft", L"Balti"},
  {"bfu", L"Gahri"},
  {"bfy", L"Bagheli"},
  {"bg", L"Bulgarian"},
  {"bgn", L"Western Balochi"},
  {"bgp", L"Eastern Balochi"},
  {"bgr", L"Bawm Chin"},
  {"bhb", L"Bhili"},
  {"bhr", L"Bara Malagasy"},
  {"bi", L"Bislama"},
  {"bin", L"Edo"},
  {"bjn", L"Banjar"},
  {"bjt", L"Balanta-Ganja"},
  {"bla", L"Siksika"},
  {"ble", L"Balanta-Kentohe"},
  {"bln", L"Southern Catanduanes Bikol"},
  {"bm", L"Bambara (Bamanankan)"},
  {"bmm", L"Northern Betsimisaraka Malagasy"},
  {"bn", L"Bengali"},
  {"bo", L"Tibetan"},
  {"bqi", L"Bakhtiari"},
  {"br", L"Breton"},
  {"bra", L"Braj"},
  {"bs", L"Bosnian"},
  {"btj", L"Bacanese Malay"},
  {"bto", L"Rinconada Bikol"},
  {"bum", L"Bulu (Cameroon)"},
  {"bve", L"Berau Malay"},
  {"bvu", L"Bukit Malay"},
  {"bxk", L"Bukusu"},
  {"bxp", L"Bebil"},
  {"bxr", L"Russia Buriat"},
  {"byn", L"Bilin"},
  {"bzc", L"Southern Betsimisaraka Malagasy"},
  {"ca", L"Catalan"},
  {"caf", L"Southern Carrier"},
  {"cbl", L"Bualkhaw Chin"},
  {"cco", L"Comaltepec Chinantec"},
  {"cdo", L"Min Dong Chinese"},
  {"ce", L"Chechen"},
  {"cfm", L"Halam (Falam Chin)"},
  {"ch", L"Chamorro"},
  {"chj", L"Ojitlán Chinantec"},
  {"chk", L"Chuukese"},
  {"chp", L"Chipewyan"},
  {"chq", L"Quiotepec Chinantec"},
  {"chz", L"Ozumacín Chinantec"},
  {"ciw", L"Chippewa"},
  {"cjy", L"Jinyu Chinese"},
  {"ckb", L"Central Kurdish"},
  {"ckt", L"Chukot"},
  {"clc", L"Chilcotin"},
  {"cld", L"Chaldean Neo-Aramaic"},
  {"cle", L"Lealao Chinantec"},
  {"cmn", L"Mandarin Chinese"},
  {"cmr", L"Mro-Khimi Chin"},
  {"cnb", L"Chinbon Chin"},
  {"cnh", L"Hakha Chin"},
  {"cnk", L"Khumi Chin"},
  {"cnl", L"Lalana Chinantec"},
  {"cnt", L"Tepetotutla Chinantec"},
  {"cnw", L"Ngawn Chin"},
  {"co", L"Corsican"},
  {"coa", L"Cocos Islands Malay"},
  {"coq", L"Coquille"},
  {"cpa", L"Palantla Chinantec"},
  {"cpe", L"English-based creoles and pidgins [family]"},
  {"cpf", L"French-based creoles and pidgins [family]"},
  {"cpx", L"Pu-Xian Chinese"},
  {"cqd", L"Chuanqiandian Cluster Miao"},
  {"cr", L"Cree"},
  {"crh", L"Crimean Tatar"},
  {"crj", L"Southern East Cree"},
  {"crk", L"Plains Cree"},
  {"crl", L"Northern East Cree"},
  {"crm", L"Moose Cree"},
  {"crp", L"Creoles and pidgins [family]"},
  {"crx", L"Carrier"},
  {"cs", L"Czech"},
  {"csa", L"Chiltepec Chinantec"},
  {"csh", L"Asho Chin"},
  {"cso", L"Sochiapam Chinantec"},
  {"csw", L"Swampy Cree"},
  {"csy", L"Siyin Chin"},
  {"ctc", L"Chetco"},
  {"ctd", L"Tedim Chin"},
  {"cte", L"Tepinapa Chinantec"},
  {"ctl", L"Tlacoatzintepec Chinantec"},
  {"cts", L"Northern Catanduanes Bikol"},
  {"cu", L"Church Slavonic"},
  {"cuc", L"Usila Chinantec"},
  {"cv", L"Chuvash"},
  {"cvn", L"Valle Nacional Chinantec"},
  {"cwd", L"Woods Cree"},
  {"cy", L"Welsh"},
  {"czh", L"Huizhou Chinese"},
  {"czo", L"Min Zhong Chinese"},
  {"czt", L"Zotung Chin"},
  {"da", L"Danish"},
  {"dao", L"Daai Chin"},
  {"de", L"German"},
  {"den", L"Slave (Athapascan)"},
  {"dgr", L"Dogrib"},
  {"dhd", L"Dhundari"},
  {"dib", L"South Central Dinka"},
  {"dik", L"Southwestern Dinka"},
  {"din", L"Dinka"},
  {"dip", L"Northeastern Dinka"},
  {"diw", L"Northwestern Dinka"},
  {"dje", L"Zarma"},
  {"djr", L"Djambarrpuyngu"},
  {"dks", L"Southeastern Dinka"},
  {"dng", L"Dungan"},
  {"doi", L"Dogri"},
  {"dsb", L"Lower Sorbian"},
  {"dty", L"Dotyali"},
  {"dup", L"Duano"},
  {"dv", L"Divehi (Dhivehi, Maldivian)"},
  {"dwu", L"Dhuwal"},
  {"dwy", L"Dhuwaya"},
  {"dyu", L"Dyula"},
  {"dz", L"Dzongkha"},
  {"ee", L"Ewe"},
  {"ekk", L"Standard Estonian"},
  {"el", L"Modern Greek (1453-)"},
  {"emk", L"Eastern Maninkakan"},
  {"en", L"English"},
  {"enb", L"Markweeta"},
  {"enf", L"Forest Enets"},
  {"enh", L"Tundra Enets"},
  {"eo", L"Esperanto"},
  {"es", L"Spanish"},
  {"esg", L"Aheri Gondi"},
  {"esi", L"North Alaskan Inupiatun"},
  {"esk", L"Northwest Alaska Inupiatun"},
  {"et", L"Estonian"},
  {"eto", L"Eton (Cameroon)"},
  {"eu", L"Basque"},
  {"eve", L"Even"},
  {"evn", L"Evenki"},
  {"ewo", L"Ewondo"},
  {"eyo", L"Keiyo"},
  {"fa", L"Persian"},
  {"fan", L"Fang (Equatorial Guinea)"},
  {"fbl", L"West Albay Bikol"},
  {"ff", L"Fulah"},
  {"ffm", L"Maasina Fulfulde"},
  {"fi", L"Finnish"},
  {"fil", L"Filipino"},
  {"fj", L"Fijian"},
  {"fo", L"Faroese"},
  {"fr", L"French"},
  {"fub", L"Adamawa Fulfulde"},
  {"fuc", L"Pulaar"},
  {"fue", L"Borgu Fulfulde"},
  {"fuf", L"Pular"},
  {"fuh", L"Western Niger Fulfulde"},
  {"fui", L"Bagirmi Fulfulde"},
  {"fuq", L"Central-Eastern Niger Fulfulde"},
  {"fur", L"Friulian"},
  {"fy", L"Western Frisian"},
  {"ga", L"Irish"},
  {"gaa", L"Ga"},
  {"gan", L"Gan Chinese"},
  {"gax", L"Borana-Arsi-Guji Oromo"},
  {"gaz", L"West Central Oromo"},
  {"gbm", L"Garhwali"},
  {"gce", L"Galice"},
  {"gd", L"Scottish Gaelic (Gaelic)"},
  {"gda", L"Gade Lohar"},
  {"gil", L"Kiribati (Gilbertese)"},
  {"gju", L"Gujari"},
  {"gl", L"Galician"},
  {"gld", L"Nanai"},
  {"gn", L"Guarani"},
  {"gno", L"Northern Gondi"},
  {"gnw", L"Western Bolivian Guaraní"},
  {"gom", L"Goan Konkani"},
  {"grt", L"Garo"},
  {"gru", L"Kistane"},
  {"gsw", L"Alsatian"},
  {"gu", L"Gujarati"},
  {"gug", L"Paraguayan Guaraní"},
  {"gui", L"Eastern Bolivian Guaraní"},
  {"guk", L"Gumuz"},
  {"gun", L"Mbyá Guaraní"},
  {"gv", L"Manx"},
  {"gwi", L"Gwichʼin"},
  {"ha", L"Hausa"},
  {"haa", L"Han"},
  {"hae", L"Eastern Oromo"},
  {"hak", L"Hakka Chinese"},
  {"har", L"Harari"},
  {"he", L"Hebrew"},
  {"hea", L"Northern Qiandong Miao"},
  {"hi", L"Hindi"},
  {"hji", L"Haji"},
  {"hlt", L"Matu Chin"},
  {"hma", L"Southern Mashan Hmong"},
  {"hmc", L"Central Huishui Hmong"},
  {"hmd", L"Large Flowery Miao"},
  {"hme", L"Eastern Huishui Hmong"},
  {"hmg", L"Southwestern Guiyang Hmong"},
  {"hmh", L"Southwestern Huishui Hmong"},
  {"hmi", L"Northern Huishui Hmong"},
  {"hmj", L"Ge"},
  {"hml", L"Luopohe Hmong"},
  {"hmm", L"Central Mashan Hmong"},
  {"hmp", L"Northern Mashan Hmong"},
  {"hmq", L"Eastern Qiandong Miao"},
  {"hms", L"Southern Qiandong Miao"},
  {"hmw", L"Western Mashan Hmong"},
  {"hmy", L"Southern Guiyang Hmong"},
  {"hmz", L"Hmong Shua"},
  {"hne", L"Chhattisgarhi"},
  {"hnj", L"Hmong Njua"},
  {"hno", L"Northern Hindko"},
  {"ho", L"Hiri Motu"},
  {"hoc", L"Ho"},
  {"hoi", L"Holikachuk"},
  {"hoj", L"Hadothi"},
  {"hr", L"Croatian"},
  {"hrm", L"Horned Miao"},
  {"hsb", L"Upper Sorbian"},
  {"hsn", L"Xiang Chinese"},
  {"ht", L"Haitian (Haitian Creole)"},
  {"hu", L"Hungarian"},
  {"huj", L"Northern Guiyang Hmong"},
  {"hup", L"Hupa"},
  {"hy", L"Armenian"},
  {"hyw", L"Western Armenian"},
  {"hz", L"Herero"},
  {"ia", L"Interlingua (International Auxiliary Language Association)"},
  {"id", L"Indonesian"},
  {"ida", L"Idakho-Isukha-Tiriki"},
  {"ie", L"Interlingue"},
  {"ig", L"Igbo"},
  {"igb", L"Ebira"},
  {"ii", L"Sichuan Yi"},
  {"ijc", L"Izon"},
  {"ik", L"Inupiaq"},
  {"ike", L"Eastern Canadian Inuktitut"},
  {"ikt", L"Inuinnaqtun"},
  {"ing", L"Degexit'an"},
  {"inh", L"Ingush"},
  {"io", L"Ido"},
  {"is", L"Icelandic"},
  {"it", L"Italian"},
  {"iu", L"Inuktitut"},
  {"ja", L"Japanese"},
  {"jak", L"Jakun"},
  {"jax", L"Jambi Malay"},
  {"jv", L"Javanese"},
  {"ka", L"Georgian"},
  {"kaa", L"Kara-Kalpak"},
  {"kab", L"Kabyle"},
  {"kam", L"Kamba (Kenya)"},
  {"kar", L"Karen [family]"},
  {"kbd", L"Kabardian"},
  {"kby", L"Manga Kanuri"},
  {"kca", L"Khanty"},
  {"kdr", L"Karaim"},
  {"kdt", L"Kuy"},
  {"kex", L"Kukna"},
  {"kfa", L"Kodava"},
  {"kfr", L"Kachhi"},
  {"kfx", L"Kullu Pahari"},
  {"kfy", L"Kumaoni"},
  {"kg", L"Kongo"},
  {"kha", L"Khasi"},
  {"khb", L"Lü"},
  {"khk", L"Halh Mongolian"},
  {"kht", L"Khamti"},
  {"ki", L"Kikuyu (Gikuyu)"},
  {"kj", L"Kuanyama"},
  {"kjh", L"Khakas"},
  {"kk", L"Kazakh"},
  {"kkz", L"Kaska"},
  {"kl", L"Greenlandic"},
  {"kln", L"Kalenjin"},
  {"km", L"Khmer"},
  {"kmb", L"Kimbundu"},
  {"kmr", L"Northern Kurdish"},
  {"kmw", L"Komo (Democratic Republic of Congo)"},
  {"kn", L"Kannada"},
  {"knc", L"Central Kanuri"},
  {"kng", L"Koongo"},
  {"knn", L"Konkani"},
  {"ko", L"Korean"},
  {"koi", L"Komi-Permyak"},
  {"koy", L"Koyukon"},
  {"kpe", L"Kpelle"},
  {"kpv", L"Komi-Zyrian"},
  {"kpy", L"Koryak"},
  {"kqs", L"Northern Kissi"},
  {"kqy", L"Koorete"},
  {"kr", L"Kanuri"},
  {"krc", L"Karachay-Balkar"},
  {"krt", L"Tumari Kanuri"},
  {"kru", L"Kurukh"},
  {"ks", L"Kashmiri"},
  {"ksh", L"Kölsch"},
  {"kss", L"Southern Kisi"},
  {"ktb", L"Kambaata"},
  {"ktu", L"Kituba (Democratic Republic of Congo)"},
  {"ktw", L"Kato"},
  {"ku", L"Kurdish"},
  {"kuu", L"Upper Kuskokwim"},
  {"kv", L"Komi"},
  {"kvb", L"Kubu"},
  {"kvr", L"Kerinci"},
  {"kw", L"Cornish"},
  {"kwy", L"San Salvador Kongo"},
  {"kxc", L"Konso"},
  {"kxd", L"Brunei"},
  {"kxu", L"Kui (India)"},
  {"ky", L"Kirghiz (Kyrgyz)"},
  {"la", L"Latin"},
  {"lad", L"Ladino"},
  {"lb", L"Luxembourgish"},
  {"lbe", L"Lak"},
  {"lbj", L"Ladakhi"},
  {"lbl", L"Libon Bikol"},
  {"lce", L"Loncong"},
  {"lcf", L"Lubu"},
  {"ldi", L"Laari"},
  {"lg", L"Ganda"},
  {"li", L"Limburgish"},
  {"lif", L"Limbu"},
  {"liw", L"Col"},
  {"lkb", L"Kabras"},
  {"lko", L"Khayo"},
  {"lks", L"Kisa"},
  {"lld", L"Ladin"},
  {"lmn", L"Lambadi"},
  {"ln", L"Lingala"},
  {"lo", L"Lao"},
  {"lri", L"Marachi"},
  {"lrm", L"Marama"},
  {"lsm", L"Saamia"},
  {"lt", L"Lithuanian"},
  {"ltg", L"Latgalian"},
  {"lto", L"Tsotso"},
  {"lts", L"Tachoni"},
  {"lu", L"Luba-Katanga"},
  {"lus", L"Lushai"},
  {"luy", L"Luyia"},
  {"luz", L"Southern Luri"},
  {"lv", L"Latvian"},
  {"lvs", L"Standard Latvian"},
  {"lwg", L"Wanga"},
  {"lzh", L"Literary Chinese"},
  {"lzz", L"Laz"},
  {"mai", L"Maithili"},
  {"mak", L"Makasar"},
  {"man", L"Mandingo"},
  {"max", L"North Moluccan Malay"},
  {"mct", L"Mengisa"},
  {"mdf", L"Moksha"},
  {"mdy", L"Male (Ethiopia)"},
  {"men", L"Mende (Sierra Leone)"},
  {"meo", L"Kedah Malay"},
  {"mfb", L"Bangka"},
  {"mg", L"Malagasy"},
  {"mh", L"Marshallese"},
  {"mhr", L"Eastern Mari"},
  {"mi", L"Maori"},
  {"mk", L"Macedonian"},
  {"mku", L"Konyanka Maninka"},
  {"ml", L"Malayalam"},
  {"mlq", L"Western Maninkakan"},
  {"mmr", L"Western Xiangxi Miao"},
  {"mn", L"Mongolian"},
  {"mnc", L"Manchu"},
  {"mnk", L"Mandinka"},
  {"mnp", L"Min Bei Chinese"},
  {"mns", L"Mansi"},
  {"mnw", L"Mon"},
  {"mpe", L"Majang"},
  {"mqg", L"Kota Bangun Kutai Malay"},
  {"mr", L"Marathi"},
  {"mrh", L"Mara Chin"},
  {"mrj", L"Western Mari"},
  {"ms", L"Malay"},
  {"msc", L"Sankaran Maninka"},
  {"msh", L"Masikoro Malagasy"},
  {"msi", L"Sabah Malay"},
  {"mt", L"Maltese"},
  {"mtr", L"Mewari"},
  {"mui", L"Musi"},
  {"mup", L"Malvi"},
  {"muq", L"Eastern Xiangxi Miao"},
  {"mvb", L"Mattole"},
  {"mve", L"Marwari (Pakistan)"},
  {"mvf", L"Peripheral Mongolian"},
  {"mwk", L"Kita Maninkakan"},
  {"mwr", L"Marwari"},
  {"my", L"Burmese"},
  {"mym", L"Me’en"},
  {"myv", L"Erzya"},
  {"na", L"Nauru"},
  {"nan", L"Min Nan Chinese"},
  {"nb", L"Norwegian Bokmål"},
  {"nd", L"North Ndebele"},
  {"ne", L"Nepali"},
  {"ng", L"Ndonga"},
  {"ngl", L"Lomwe"},
  {"ngo", L"Ngoni"},
  {"nhd", L"Chiripá"},
  {"niq", L"Nandi"},
  {"niv", L"Gilyak"},
  {"njz", L"Nyishi"},
  {"nl", L"Dutch"},
  {"nle", L"East Nyala"},
  {"nn", L"Norwegian Nynorsk (Nynorsk, Norwegian)"},
  {"no", L"Norwegian"},
  {"nod", L"Northern Thai"},
  {"npi", L"Nepali"},
  {"nqo", L"N’Ko"},
  {"nr", L"South Ndebele"},
  {"nsk", L"Naskapi"},
  {"nv", L"Navajo"},
  {"ny", L"Chichewa (Chewa, Nyanja)"},
  {"nyd", L"Nyore"},
  {"nyn", L"Nyankole"},
  {"oc", L"Occitan (post 1500)"},
  {"oj", L"Ojibwa"},
  {"ojc", L"Central Ojibwa"},
  {"ojg", L"Eastern Ojibwa"},
  {"ojs", L"Severn Ojibwa"},
  {"ojw", L"Western Ojibwa"},
  {"oki", L"Okiek"},
  {"okm", L"Middle Korean (10th-16th cent.)"},
  {"om", L"Oromo"},
  {"or", L"Odia (formerly Oriya)"},
  {"orc", L"Orma"},
  {"orn", L"Orang Kanaq"},
  {"ors", L"Orang Seletar"},
  {"ory", L"Odia (formerly Oriya)"},
  {"os", L"Ossetian"},
  {"otw", L"Ottawa"},
  {"pa", L"Punjabi"},
  {"pap", L"Papiamento"},
  {"pbt", L"Southern Pashto"},
  {"pbu", L"Northern Pashto"},
  {"pce", L"Ruching Palaung"},
  {"pck", L"Paite Chin"},
  {"pel", L"Pekal"},
  {"pes", L"Iranian Persian"},
  {"pga", L"Sudanese Creole Arabic"},
  {"pi", L"Pali"},
  {"pko", L"Pökoot"},
  {"pl", L"Polish"},
  {"pll", L"Shwe Palaung"},
  {"plp", L"Palpa"},
  {"plt", L"Plateau Malagasy"},
  {"prs", L"Dari"},
  {"ps", L"Pashto"},
  {"pse", L"Central Malay"},
  {"pst", L"Central Pashto"},
  {"pt", L"Portuguese"},
  {"qu", L"Quechua"},
  {"qub", L"Huallaga Huánuco Quechua"},
  {"qud", L"Calderón Highland Quichua"},
  {"quf", L"Lambayeque Quechua"},
  {"qug", L"Chimborazo Highland Quichua"},
  {"quk", L"Chachapoyas Quechua"},
  {"qul", L"North Bolivian Quechua"},
  {"qup", L"Southern Pastaza Quechua"},
  {"qur", L"Yanahuanca Pasco Quechua"},
  {"qus", L"Santiago del Estero Quichua"},
  {"quw", L"Tena Lowland Quichua"},
  {"qux", L"Yauyos Quechua"},
  {"quy", L"Ayacucho Quechua"},
  {"qva", L"Ambo-Pasco Quechua"},
  {"qvc", L"Cajamarca Quechua"},
  {"qve", L"Eastern Apurímac Quechua"},
  {"qvh", L"Huamalíes-Dos de Mayo Huánuco Quechua"},
  {"qvj", L"Loja Highland Quichua"},
  {"qvl", L"Cajatambo North Lima Quechua"},
  {"qvm", L"Margos-Yarowilca-Lauricocha Quechua"},
  {"qvn", L"North Junín Quechua"},
  {"qvo", L"Napo Lowland Quechua"},
  {"qvp", L"Pacaraos Quechua"},
  {"qvs", L"San Martín Quechua"},
  {"qvw", L"Huaylla Wanca Quechua"},
  {"qvz", L"Northern Pastaza Quichua"},
  {"qwa", L"Corongo Ancash Quechua"},
  {"qwc", L"Classical Quechua"},
  {"qws", L"Sihuas Ancash Quechua"},
  {"qxa", L"Chiquián Ancash Quechua"},
  {"qxc", L"Chincha Quechua"},
  {"qxh", L"Panao Huánuco Quechua"},
  {"qxl", L"Salasaca Highland Quichua"},
  {"qxn", L"Northern Conchucos Ancash Quechua"},
  {"qxo", L"Southern Conchucos Ancash Quechua"},
  {"qxp", L"Puno Quechua"},
  {"qxr", L"Cañar Highland Quichua"},
  {"qxt", L"Santa Ana de Tusi Pasco Quechua"},
  {"qxu", L"Arequipa-La Unión Quechua"},
  {"qxw", L"Jauja Wanca Quechua"},
  {"rag", L"Logooli"},
  {"rbb", L"Rumai Palaung"},
  {"rbl", L"Miraya Bikol"},
  {"rki", L"Rakhine"},
  {"rm", L"Romansh"},
  {"rmc", L"Carpathian Romani"},
  {"rmf", L"Kalo Finnish Romani"},
  {"rml", L"Baltic Romani"},
  {"rmn", L"Balkan Romani"},
  {"rmo", L"Sinte Romani"},
  {"rmw", L"Welsh Romani"},
  {"rmz", L"Marma"},
  {"rn", L"Rundi"},
  {"rnl", L"Ranglong"},
  {"ro", L"Romanian"},
  {"rom", L"Romany"},
  {"ru", L"Russian"},
  {"rue", L"Rusyn"},
  {"rw", L"Kinyarwanda"},
  {"rwr", L"Marwari (India)"},
  {"sa", L"Sanskrit"},
  {"sah", L"Yakut"},
  {"sam", L"Samaritan Aramaic"},
  {"sc", L"Sardinian"},
  {"sck", L"Sadri"},
  {"scs", L"North Slavey"},
  {"sd", L"Sindhi"},
  {"sdc", L"Sassarese Sardinian"},
  {"sdh", L"Southern Kurdish"},
  {"sdn", L"Gallurese Sardinian"},
  {"se", L"Northern Sami"},
  {"seh", L"Sena"},
  {"sek", L"Sekani"},
  {"sez", L"Senthang Chin"},
  {"sfm", L"Small Flowery Miao"},
  {"sg", L"Sango"},
  {"sgc", L"Kipsigis"},
  {"sgw", L"Sebat Bet Gurage"},
  {"shu", L"Chadian Arabic"},
  {"si", L"Sinhala (Sinhalese)"},
  {"sjd", L"Kildin Sami"},
  {"sjo", L"Xibe"},
  {"sk", L"Slovak"},
  {"skg", L"Sakalava Malagasy"},
  {"skr", L"Saraiki"},
  {"sl", L"Slovenian"},
  {"sm", L"Samoan"},
  {"sma", L"Southern Sami"},
  {"smj", L"Lule Sami"},
  {"smn", L"Inari Sami"},
  {"sms", L"Skolt Sami"},
  {"sn", L"Shona"},
  {"so", L"Somali"},
  {"spv", L"Sambalpuri"},
  {"spy", L"Sabaot"},
  {"sq", L"Albanian"},
  {"sr", L"Serbian"},
  {"src", L"Logudorese Sardinian"},
  {"sro", L"Campidanese Sardinian"},
  {"srs", L"Sarsi"},
  {"ss", L"Swati"},
  {"ssh", L"Shihhi Arabic"},
  {"st", L"Southern Sotho"},
  {"stv", L"Silt'e"},
  {"su", L"Sundanese"},
  {"suq", L"Suri"},
  {"sv", L"Swedish"},
  {"sw", L"Swahili"},
  {"swb", L"Maore Comorian"},
  {"swc", L"Congo Swahili"},
  {"swh", L"Swahili"},
  {"swv", L"Shekhawati"},
  {"syc", L"Classical Syriac"},
  {"ta", L"Tamil"},
  {"taa", L"Lower Tanana"},
  {"taq", L"Tamasheq"},
  {"tau", L"Upper Tanana"},
  {"tcb", L"Tanacross"},
  {"tce", L"Southern Tutchone"},
  {"tcp", L"Tawr Chin"},
  {"tcy", L"Tulu"},
  {"tcz", L"Thado Chin"},
  {"tdx", L"Tandroy-Mahafaly Malagasy"},
  {"te", L"Telugu"},
  {"tec", L"Terik"},
  {"tem", L"Timne"},
  {"tfn", L"Tanaina"},
  {"tg", L"Tajik"},
  {"tgj", L"Tagin"},
  {"tgx", L"Tagish"},
  {"th", L"Thai"},
  {"tht", L"Tahltan"},
  {"thv", L"Tahaggart Tamahaq"},
  {"thz", L"Tayart Tamajeq"},
  {"ti", L"Tigrinya"},
  {"tig", L"Tigre"},
  {"tk", L"Turkmen"},
  {"tkg", L"Tesaka Malagasy"},
  {"tl", L"Tagalog"},
  {"tmw", L"Temuan"},
  {"tn", L"Tswana"},
  {"to", L"Tonga (Tonga Islands)"},
  {"tod", L"Toma"},
  {"toi", L"Tonga (Zambia)"},
  {"tol", L"Tolowa"},
  {"tr", L"Turkish"},
  {"tru", L"Turoyo"},
  {"ts", L"Tsonga"},
  {"tt", L"Tatar"},
  {"ttm", L"Northern Tutchone"},
  {"ttq", L"Tawallammat Tamajaq"},
  {"tuu", L"Tututni"},
  {"tuy", L"Tugen"},
  {"tw", L"Twi"},
  {"txc", L"Tsetsaut"},
  {"txy", L"Tanosy Malagasy"},
  {"ty", L"Tahitian"},
  {"tyv", L"Tuvinian"},
  {"ubl", L"Buhi'non Bikol"},
  {"ug", L"Uyghur"},
  {"uk", L"Ukrainian"},
  {"unr", L"Mundari"},
  {"ur", L"Urdu"},
  {"urk", L"Urak Lawoi'"},
  {"uz", L"Uzbek"},
  {"uzn", L"Northern Uzbek"},
  {"uzs", L"Southern Uzbek"},
  {"ve", L"Venda"},
  {"vi", L"Vietnamese"},
  {"vkk", L"Kaur"},
  {"vkt", L"Tenggarong Kutai Malay"},
  {"vls", L"Vlaams"},
  {"vmw", L"Makhuwa"},
  {"vo", L"Volapük"},
  {"wa", L"Walloon"},
  {"wbm", L"Wa"},
  {"wbr", L"Wagdi"},
  {"wlc", L"Mwali Comorian"},
  {"wle", L"Wolane"},
  {"wlk", L"Wailaki"},
  {"wni", L"Ndzwani Comorian"},
  {"wo", L"Wolof"},
  {"wry", L"Merwari"},
  {"wsg", L"Adilabad Gondi"},
  {"wuu", L"Wu Chinese"},
  {"xal", L"Kalmyk"},
  {"xan", L"Xamtanga"},
  {"xh", L"Xhosa"},
  {"xmm", L"Manado Malay"},
  {"xmv", L"Antankarana Malagasy"},
  {"xmw", L"Tsimihety Malagasy"},
  {"xnr", L"Kangri"},
  {"xsl", L"South Slavey"},
  {"xwo", L"Written Oirat"},
  {"ydd", L"Eastern Yiddish"},
  {"yi", L"Yiddish"},
  {"yih", L"Western Yiddish"},
  {"yo", L"Yoruba"},
  {"yrk", L"Nenets"},
  {"yue", L"Yue Chinese"},
  {"za", L"Zhuang"},
  {"zch", L"Central Hongshuihe Zhuang"},
  {"zdj", L"Ngazidja Comorian"},
  {"zeh", L"Eastern Hongshuihe Zhuang"},
  {"zgb", L"Guibei Zhuang"},
  {"zgm", L"Minz Zhuang"},
  {"zgn", L"Guibian Zhuang"},
  {"zh", L"Chinese"},
  {"zhd", L"Dai Zhuang"},
  {"zhn", L"Nong Zhuang"},
  {"zlj", L"Liujiang Zhuang"},
  {"zlm", L"Malay"},
  {"zln", L"Lianshan Zhuang"},
  {"zlq", L"Liuqian Zhuang"},
  {"zmi", L"Negeri Sembilan Malay"},
  {"zne", L"Zande"},
  {"zom", L"Zou"},
  {"zqe", L"Qiubei Zhuang"},
  {"zsm", L"Standard Malay"},
  {"zu", L"Zulu"},
  {"zum", L"Kumzari"},
  {"zyb", L"Yongbei Zhuang"},
  {"zyg", L"Yang Zhuang"},
  {"zyj", L"Youjiang Zhuang"},
  {"zyn", L"Yongnan Zhuang"},
  {"zzj", L"Zuojiang Zhuang"},
};
