name: Mediaportal / Jira

on:
  push:
    # On Push to Master branch
    branches:
      - 'MP1-**'
    # Ignore all Tags / Release
    tags-ignore:
      - '**'

  workflow_call:
    inputs:
      retention-logs:
        description: "Retention Period for Log files. Default is 1"
        default: 3
        required: false
        type: number
      retention-build:
        description: "Retention Period for Setup files. Default is 90"
        default: 3
        required: false
        type: number

jobs:
  build:
    name: Mediaportal Build
    uses: ./.github/workflows/mediaportal.yml
    with:
      retention-logs: ${{ inputs.retention-logs || 3 }}
      retention-build: ${{ inputs.retention-build || 3 }}

  ci-status:
    name: Status
    runs-on: ubuntu-latest
    needs:
      - build
    if: always()
    steps:
      - name: Success
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0
      - name: Failure
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1
