name: Mediaportal / Jira

on:
  push:
    # On Push to Master branch
    branches: 
      - 'MP1-**'
    # Ignore all Tags / Release
    tags-ignore:
      - '**'   
  workflow_call:

jobs:
  build:
    strategy:
      matrix:
        architecture: [x86, x64]  

    name: Build Mediaportal

    runs-on: windows-2019
    
    steps:
    - name: Setup Visual Studio 2019
      uses: microsoft/setup-msbuild@v1.3
      with:
        vs-version: 16.11

    - name: Link to Visual Studio 2019 Community
      run: |
        mklink /J "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community" "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise"
      shell: cmd

    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        java-version: 8
        architecture: x86
        distribution: temurin

    - name: Setup NSIS
      run: |
        choco install --yes nsis --version=3.08 --force

    - name: Git Checkout
      uses: actions/checkout@v4

    - name: Git Submodule Update
      run: |
        git submodule update --init --recursive

    - name: Build
      run: |
        BuildFullinstaller.cmd LOG ${{ matrix.architecture }}
      working-directory: ${{ github.workspace }}\Build
      shell: cmd

    - name: Upload Artifact / Build result file
      uses: actions/upload-artifact@v3
      if: ${{ always() }}
      with:
        name: Build result file ${{ matrix.architecture }}
        path: |
          ${{ github.workspace }}\Build\BuildFullInstaller.log
        retention-days: 3

    - name: Upload Artifact / Mediaportal setup file
      uses: actions/upload-artifact@v3
      if: ${{ success() }}
      with:
        name: Mediaportal setup file ${{ matrix.architecture }}
        path: |
          ${{ github.workspace }}\Release\MediaPortalSetup_*.exe
        if-no-files-found: error
        retention-days: 3
