name: "Workflow / Pull Request Labeler"

on:
  pull_request:
    types: [opened, edited]
    
jobs:
  labeler:
    name: Add labels to Pull Request

    runs-on: ubuntu-latest

    steps:
    - name: Add labels to Pull Request
      uses: github/issue-labeler@v3.3
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/labeler.yml
        enable-versioned-regex: 0
        include-title: 1
