name: "Workflow / Stale"

on:
  schedule:
    - cron: "0 12 * * 1"
  workflow_dispatch:

permissions:
  pull-requests: write

jobs:
  stale:
    name: Stale
    runs-on: ubuntu-latest
    steps:
      # The 90 day stale policy for PRs
      # Used for:
      # - PRs
      # - No PRs marked as no-stale
      # - No issues (-1)
      - name: 90 days stale PRs policy
        uses: actions/stale@v10
        with:
          days-before-stale: 90
          days-before-close: 7
          days-before-issue-stale: -1
          days-before-issue-close: -1
          operations-per-run: 150
          remove-stale-when-updated: true
          stale-pr-label: "stale"
          exempt-pr-labels: "no-stale,need-help,WIP"
          stale-pr-message: >
            There hasn't been any activity on this pull request recently. This
            pull request has been automatically marked as stale because of that
            and will be closed if no further activity occurs within 7 days.

            Thank you for your contributions.
