name: Workflow / YAML lint

on:
  push:
    branches: [main]
    paths:
      - "**.yaml"
      - "**.yml"
  pull_request:
    paths:
      - "**.yaml"
      - "**.yml"
  workflow_dispatch:

jobs:
  yamllint:
    name: 🧹 Yaml Lint
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out configuration from GitHub
        uses: actions/checkout@v7
      - name: 🚀 Run yamllint
        run: yamllint --strict .
